- changelog.d/16758.misc
- docs/.sample_config_header.yaml
I accidentally broke it during the move by removing a trailing new line.
> Fix sample config doc CI

- changelog.d/16761.bugfix
- synapse/http/server.py
- synapse/rest/synapse/client/password_reset.py
- tests/rest/client/test_account.py
Previously, the response status of `HTMLResource` was hardcoded as `200`. However, for proper redirection after the user verifies their email, we require the status to be `302`. This PR addresses that issue by using `code` as response status.
> Fix email verification redirection

- changelog.d/16775.bugfix
- synapse/handlers/relations.py
This is an extra response parameter just added to MSC3981. In the current impl, the recursion depth is always 3, so this just returns a static 3 if the recurse parameter is supplied.
> Add recursion_depth to /relations if recursing

- changelog.d/16762.misc
- synapse/events/__init__.py
- synapse/handlers/admin.py
- synapse/handlers/room.py
- synapse/handlers/sync.py
- synapse/storage/databases/main/stream.py
We remove these fields as they're just duplicating data the event already stores, and (for reasons :shushing_face:) I'd like to simplify the class to only store simple types.
I'm not entirely convinced that we shouldn't instead add helper methods to the event class to generate stream tokens, but I don't really think that's where they belong either
> Simplify internal metadata class.

- changelog.d/16759.feature
- synapse/federation/transport/server/__init__.py
- synapse/handlers/room_list.py
- tests/handlers/test_room_list.py
The idea here being that the directory server shouldn't advertise rooms to a requesting server is the requesting server would not be allowed to join or participate in the room.
Base: `develop` 
Original commit schedule, with full messages:
<ol>
<li>
Pass `from_federation_origin` down into room list retrieval code 
</li>
<li>
Don't cache /publicRooms response for inbound federated requests 
</li>
<li>
fixup! Don't cache /publicRooms response for inbound federated requests 
</li>
<li>
Cap the number of /publicRooms entries to 100 
</li>
<li>
Simplify code now that you can't request unlimited rooms 
</li>
<li>
Filter out rooms from federated requests that don't have the correct ACL 
</li>
<li>
Request a handful more when filtering ACLs so that we can try to avoid shortchanging the requester …
> Filter out rooms from the room directory being served to other homeservers when those rooms block that homeserver by their Access Control Lists.

- changelog.d/16778.doc
- docs/usage/configuration/logging_sample_config.md
This PR adds a link to the Request Log Format page from the Logging Sample Config page. I observed someone find one, but not the other, so this is to add a helpful bridge.
At a glance, I think ideally both of these pages would be combined, or made sub-pages of a general "Logging" page. But this is a quick fix for now.
> Add a link to the Request log format page from Logging Sample Config

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/tests.yml
- changelog.d/16776.misc
Since we don't require one anymore.
> Remove CI check for sign off

- .github/workflows/tests.yml
- changelog.d/16781.misc
Otherwise if you hit the `Enable auto-merge` button and the linting fails the PR is still aut-merged.
> Fix auto-merge CI to correctly wait for linting.

- changelog.d/16766.misc
- synapse/storage/databases/main/devices.py
Otherwise for users with large numbers of devices this can cause a lot of woe.
> Split up deleting devices into batches

- changelog.d/16788.misc
- synapse/handlers/federation_event.py
Sometimes we fail to fetch events during backfill due to missing state, and we often end up querying the same bad events periodically (as people backpaginate). In such cases its likely we will continue to fail to get the state, and therefore we should try *before* loading the state that we have from the DB (as otherwise it's wasted DB and memory).
> Pull less state out if we fail to backfill

- changelog.d/16806.misc
- synapse/config/oidc.py
In previous versions of authlib using `client_secret_basic` without a `client_secret` would result in an invalid auth header.  Since authlib 1.3 it throws an exception.
The configuration may be accepted in by very lax servers, so we don't want to deny it outright. Instead, let's default the `client_auth_method` to `none`, which does the right thing. If the config specifies `client_auth_method` and no `client_secret` then that is going to be bogus and we should reject it
> Correctly handle OIDC config with no `client_secret` set

- debian/rules
Broke in https://github.com/element-hq/synapse/pull/16802
> Fix building of deps after bump of `pillow` version

- changelog.d/16787.feature
- synapse/rest/client/versions.py
Fixes/Closes: https://github.com/element-hq/synapse/issues/16786
Signed-off-by: Hanadi <hanadi.tamimi@gmail.com>
> feat: add msc4028 to versions api

- changelog.d/16808.misc
- scripts-dev/release.py
We still publish to the old place.
> Fix release announcements docker link

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- changelog.d/16810.doc
- docs/development/contributing_guide.md
This happened during the migration
> Fix broken links in issue template

- changelog.d/16811.misc
- docs/usage/configuration/config_documentation.md
- synapse/handlers/room.py
- tests/config/test_room_directory.py
- tests/handlers/test_directory.py
Prior to this PR, if a request to create a public (public as in published to the rooms directory) room violated the room list publication rules set in the [config](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#room_list_publication_rules), the request to create the room was denied and the room was not created.  
This PR changes the behavior such that when a request to create a room published to the directory violates room list publication rules, the room is still created but the room is not published to the directory.
> Allow room creation but not publishing to continue if room publication rules are violated when creating a new room.

- changelog.d/16831.doc
- docs/reverse_proxy.md
More info [here](https://www.nginx.com/blog/nginx-plus-r30-released/).
Nginx threw error's at me when I used all the options of the doc
> listen http2 deprecated nginx (updating documentation)

- changelog.d/16828.misc
- docker/configure_workers_and_start.py
Pulled out of #16803 since the drive-by cleanup was maybe not as drive-by as I had hoped.
Base: `develop` 
Original commit schedule, with full messages:
<ol>
<li>
Add a --generate-only option 
</li>
</ol>
> Add a `--generate-only` option to the Complement launcher.

- changelog.d/16841.misc
- synapse/storage/databases/main/end_to_end_keys.py
This helps with bot accounts with lots of non-e2e devices.
The change is basically to change the order of the join for the case of using `INNER JOIN`
> Speed up e2e device keys queries for bot accounts

- .github/workflows/release-artifacts.yml
- changelog.d/16847.misc
Partially reverts #16796
This is causing errors of the form:
```
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
for the debs and wheels stages.
There were breaking changes that weren't included in the dependabot changelog (:/): https://github.com/actions/upload-artifact#breaking-changes
Base: `release-v1.100` 
Original commit schedule, with full messages:
<ol>
<li>
Downgrade the `upload-artifact` and `download-artifact` actions to v3 
</li>
</ol>
> Downgrade the `download-artifact` and `upload-artifact` actions to v3 due to breaking changes.

- changelog.d/16854.doc
- docs/setup/installation.md
ICU is an optional dependency and also a pain to install. Mention that you can just not install it and still get a working installation.
> Update docs for MacOS installs

- changelog.d/16842.misc
- synapse/rest/client/relations.py
Now that the MSC3981 has passed FCP
https://github.com/matrix-org/matrix-js-sdk/pull/4023 marks the API as stable in 1.10 so js-sdk will start sending it unprefixed when we advertise 1.10 support.
(run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run- …
> Accept unprefixed form of MSC3981 recurse parameter

- changelog.d/16893.bugfix
- synapse/storage/databases/main/event_federation.py
This basically reverts a change that was in https://github.com/element-hq/synapse/pull/16833, where we reduced the batching. 
The smaller batching can cause performance issues on busy servers and databases.
> Increase batching when fetching auth chains

- changelog.d/16894.bugfix
- synapse/crypto/keyring.py
Otherwise if we've stacked a bunch of requests for the keys of a server, we'll end up sending lots of concurrent requests for its keys, needlessly.
> Only do one concurrent fetch per server in keyring

- changelog.d/16909.misc
- synapse/config/registration.py
- synapse/handlers/device.py
List of users not to send out device list updates for when they register new devices. This is useful to handle bot accounts.
This is undocumented as its mostly a hack to test on matrix.org.
Note: This will still send out device list updates if the device is later updated, e.g. end to end keys are added.
> Add a config to not send out device list updates for specific users

- changelog.d/16881.feature
- synapse/push/mailer.py
This adds a counter `synapse_emails_sent_total` for emails sent. They are broken down by `type`, which are `password_reset`, `registration`, `add_threepid`, `notification` (matching …
> Add metric for emails sent

- changelog.d/16927.bugfix
- synapse/storage/databases/main/receipts.py
MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/4102
Tests: https://github.com/matrix-org/complement/pull/709
> bugfix: always prefer unthreaded receipt when >1 exist (MSC4102)

- changelog.d/16903.bugfix
- synapse/handlers/federation_event.py
Hopefully fixes the issue #16895
> Don't lock up when joining large rooms

- changelog.d/16768.doc
- docs/reverse_proxy.md
The existing example does not highlight SNI as being of importance, due to "default_backend" being used.
> Add HAProxy example for single port operation

- changelog.d/16946.doc
- docker/complement/README.md
> Better complement docs

- changelog.d/16951.doc
- docs/upgrade.md
- docs/usage/administration/admin_faq.md
> Add docs on upgrading from a very old version

- changelog.d/16954.bugfix
- synapse/storage/databases/main/event_push_actions.py
Reverts element-hq/synapse#16954. This was a partial fix for https://github.com/element-hq/synapse/pull/16756, which we've now reverted in https://github.com/element-hq/synapse/issues/16979.
Thus, the partial fix can be reverted as well.
This PR does not require a changelog, and deletes the changelog of https://github.com/element-hq/synapse/issues/16979.
> Revert "Ignore notification counts from rooms you've left"

- changelog.d/16973.bugfix
- docs/modules/third_party_rules_callbacks.md
- synapse/module_api/callbacks/third_party_event_rules_callbacks.py
- synapse/storage/controllers/state.py
Since Synapse 1.76.0, any module which registers a `on_new_event` callback would brick the ability to join remote rooms.
This is because this callback tried to get the full state of the room, which would end up in a deadlock.
Related: https://github.com/matrix-org/synapse-auto-accept-invite/issues/18
The following module would brick the ability to join remote rooms:
```python
from typing import Any, Dict, Literal, Union
import logging
from synapse.module_api import ModuleApi, EventBase
logger = logging.getLogger(__name__)
class MyModule:
def __init__(self, config: None, api: ModuleApi):
self._api = api
self._config = config
self._api.register_third_party_rules_callbacks(
on_new_event=self.on_new_event,
)
async def on_new_event(self, event: EventBase, _state_map: Any) -> None: …
```
> Fix joining remote rooms when a `on_new_event` callback is registered

- changelog.d/16947.feature
- synapse/api/errors.py
- synapse/config/experimental.py
- tests/api/test_errors.py
- tests/rest/client/test_login.py
> Stabilize support for Retry-After header (MSC4014)

- changelog.d/16968.bugfix
- synapse/event_auth.py
This PR aims to fix #16895, caused by a regression in #7 and not fixed by #16903. The PR #16903 only fixes a starvation issue, where the CPU isn't released. There is a second issue, where the execution is blocked. This theory is supported by the flame graphs provided in #16895 and the fact that I see the CPU usage reducing and far below the limit.
Since the changes in #7, the method `check_state_independent_auth_rules` is called with the additional parameter `batched_auth_events`:
https://github.com/element-hq/synapse/blob/6fa13b4f927c10b5f4e9495be746ec28849f5cb6/synapse/handlers/federation_event.py#L1741-L1743
It makes the execution enter this if clause, introduced with #15195
https://github.com/element-hq/synapse/blob/6fa13b4f927c10b5f4e9495be746ec28849f5cb6/synapse/event_auth.py#L178-L1 …
> Prevent locking up while processing batched_auth_events

- changelog.d/16986.misc
- pyproject.toml
A new poetry-core version was released. See if CI is happy. Required for the latest Fedora Synapse package.
> Raise poetry-core version cap to 1.9.0

- changelog.d/16919.misc
- docker/prefix-log
Background: we have a `matrixdotorg/synapse-workers` docker image, which is intended for running multiple workers within the same container. That image includes a `prefix-log` script which, for each line printed to stdout or stderr by one of the processes, prepends the name of the process.
This commit disables buffering in that script, so that lines are logged quickly after they are printed. This makes it much easier to understand the output, since they then come out in a natural order.
> Multi-worker-docker-container: disable log buffering

- changelog.d/16840.misc
- synapse/handlers/worker_lock.py
- tests/handlers/test_worker_lock.py
- tests/utils.py
When a lot of locks are waiting for a single lock, notifying all locks independently with `call_later` on each release is really costly and incurs some kind of async contention, where the CPU is spinning a lot for not much.
The included test is taking around 30s before the change, and 0.5s after.
It was found following failing tests with https://github.com/element-hq/synapse/pull/16827.
> Improve lock performance when a lot of locks are waiting

- changelog.d/16892.doc
- docs/usage/administration/useful_sql_for_admins.md
Originally taken from https://github.com/matrix-org/synapse/issues/7418#issuecomment-632166605. Motivated by a recent session of needing to quickly dig this query out to fix a running deployment.
> Add query to update local cache of a remote user's device list to docs

- changelog.d/16949.bugfix
- synapse/handlers/sync.py
Fixes https://github.com/element-hq/synapse/issues/16948. If the `join` and the `leave` are in the same sync response, we need to count them as a "left" user.
> `/sync`: Fix edge-case in calculating the "device_lists" response

- changelog.d/16953.misc
- tests/api/test_auth.py
This is needed, because the netaddr package removed support for the implicit prefix form in version 1.0.0:
https://github.com/netaddr/netaddr/pull/360
> Specify IP subnet literals in canonical form

- changelog.d/16974.misc
- docs/sso_mapping_providers.md
- synapse/handlers/oidc.py
As done for SAML mapping provider, let's pass the module API to the OIDC one so the mapper can do more logic in its code.
> Pass module API to OIDC mapping provider

- changelog.d/16908.misc
- synapse/api/constants.py
- synapse/handlers/message.py
- synapse/handlers/sync.py
- tests/handlers/test_message.py
- tests/handlers/test_sync.py
> Improve event validation

- changelog.d/16985.misc
- docker/complement/conf/postgres.supervisord.conf
- docker/complement/conf/start_for_complement.sh
I have a use case where I'd like the Synapse image to start up a postgres instance that I can use, but don't want to force Synapse to use postgres as well.
This commit prevents postgres from being started when it has already been explicitly enabled elsewhere.
> Prevent `start_for_complement.sh` from setting `START_POSTGRES` to `false` when it's already set

- docs/setup/installation.md
Existing link to https://hub.docker.com/r/vectorim/synapse gives 404. Assuming this docker hub link is a typo.
Checked to see if I needed to switch docker hub image target, post ownership change of synapse. Saw the docker image thread (in issues), and that the new versions are still posted to matrixorg/synapse. 
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end …
> Update link, in installation guide, for docker hub synapse images

- docs/postgres.md
`synapse_port_db` with --curses will give a python exception and exit when terminal is too small.
The error given is non-descriptive and initially looks like a bug within the `synapse_port_db` script, but is an exception thrown by Curses. This addition makes a note of that to help future searches. …
> Add note to using --curses under sqlite porting

- changelog.d/17017.misc
- tests/server.py
When running unit tests, we patch the database connection pool so that it runs queries "synchronously". This is ok, except that if any queries are launched before we do the patching, those queries get left in limbo and never complete.
To fix this, let's change the way we do the switcheroo, by patching out the method which creates the connection pool in the first place.
> Patch the db conn pool sooner in tests

- changelog.d/16972.feature
- synapse/handlers/oidc.py
> OIDC: try to JWT decode userinfo response if JSON parsing failed

- changelog.d/16978.docker
- docker/start.py
Fixes https://github.com/element-hq/synapse/issues/16824, https://github.com/element-hq/synapse/issues/15202 (and just generally makes Synapse w/ Docker work by default again)
> generate configuration with correct user in start.py for docker

- changelog.d/17010.bugfix
- synapse/handlers/deactivate_account.py
- synapse/storage/databases/main/roommember.py
- tests/handlers/test_deactivate_account.py
Fixes https://github.com/element-hq/synapse/issues/16861
> Fix reject knocks on deactivating account

- changelog.d/16990.bugfix
- synapse/handlers/read_marker.py
- synapse/storage/databases/main/events_worker.py
- tests/rest/client/test_read_marker.py
I was having some room in which the `m.fully_read` would never update, despite synapse returning 200 whenever a client tried to do so. Upon checking the `event_id` that was being persisted in account data, and looking it up in my database, it appeared to be in a different room than the room I was trying to set the read marker for.
Accordingly, it should be a good idea to ensure the room_id is appropriate when comparing event ordering before setting the fully_read marker, to avoid having events in different rooms preventing us from setting an appropriate marker.
- Use markdown where …
> Do not refuse to set read_marker if previous event_id is in wrong room

- changelog.d/17031.feature
- synapse/http/client.py
Requests may require a User-Agent header, and the change in #16972 accidentally removed it, resulting in requests getting rejected causing login to fail.
> Fix OIDC login regression

- changelog.d/17037.feature
- changelog.d/17038.feature
- docker/configure_workers_and_start.py
- docs/workers.md
- synapse/config/workers.py
- synapse/handlers/room_member.py
- synapse/replication/tcp/handler.py
- synapse/rest/client/push_rule.py
- synapse/storage/databases/main/push_rule.py
> Fixups to new push stream

- changelog.d/17044.misc
- synapse/storage/databases/main/event_federation.py
Since these queries are duplicated in two places.
> Refactor chain fetching

- changelog.d/17045.misc
- synapse/storage/databases/main/registration.py
This was causing sequential scans when using refresh tokens.
> Add missing index to `access_tokens` table

- changelog.d/16932.bugfix
- synapse/handlers/sync.py
- tests/handlers/test_sync.py
- tests/rest/client/utils.py
This PR fixes a very, very niche edge-case, but I've got some more work coming which will otherwise make the problem worse.
The bug happens when the syncing user leaves a room, and has a sync filter which includes "left" rooms, but sets the timeline limit to 0. In that case, the state returned in the `state` section is calculated incorrectly.
The fix is to pass a token corresponding to the point that the user leaves the room through to `compute_state_delta`.
> Fix bug in `/sync` response for archived rooms

- changelog.d/16930.bugfix
- synapse/handlers/sync.py
- tests/handlers/test_sync.py
Fix a long-standing issue which could cause state to be omitted from the sync response if the last event was filtered out.
Fixes: https://github.com/element-hq/synapse/issues/16928
~~Based on #16932~~
> `/sync`: fix bug in calculating `state` response

- changelog.d/16930.bugfix
- changelog.d/16932.bugfix
- changelog.d/16942.bugfix
- synapse/handlers/sync.py
- tests/handlers/test_sync.py
Unfortunately, the optimisation we applied here for non-gappy syncs is not actually valid.
Fixes https://github.com/element-hq/synapse/issues/16941.
~~Based on https://github.com/element-hq/synapse/pull/16930.~~
Requires https://github.com/matrix-org/sytest/pull/1374.
> Fix bug in calculating state for non-gappy syncs

- changelog.d/17049.misc
- synapse/storage/databases/main/event_push_actions.py
Before we were pulling out *all* read receipts for a user for every event we pushed. Instead let's only pull out the relevant receipts.
This also pulled out the event rows for each receipt, causing load on the events table.
> Pull out fewer receipts from DB when doing push

- changelog.d/17064.bugfix
- synapse/handlers/sync.py
PR #16942 removed an invalid optimisation that avoided pulling out state for non-gappy syncs. This causes a large increase in DB usage. c.f. #16941 for why that optimisation was wrong.
However, we can still optimise in the simple case where the events in the timeline are a linear chain without any branching/merging of the DAG.
cc. @richvdh
> Add back fast path for non-gappy syncs

- changelog.d/17065.bugfix
- synapse/handlers/sync.py
Forget a line, and an empty batch is trivially linear.
c.f. #17064
> Fixups to #17064

- changelog.d/17033.bugfix
- synapse/handlers/room.py
I made a silly mistake in https://github.com/matrix-org/synapse/pull/16677.
Sorry for that :facepalm: 
> Fix PR #16677, a parameter was missing in a function call

- changelog.d/17043.bugfix
- rust/src/push/base_rules.rs
Fixes #17039.
Changed to default underlines rules in order in file synapse/rust/src/push/base_rules.rs
.m.rule.call
.m.rule.encrypted_room_one_to_one
.m.rule.room_one_to_one
...
> #17039 Issue: Update base_rules.rs

- changelog.d/17066.bugfix
- synapse/handlers/sync.py
- tests/handlers/test_sync.py
Refinement of #17064 
cc @richvdh
> Also check if first event matches the last in prev batch

- changelog.d/17023.feature
- synapse/config/experimental.py
- synapse/rest/client/relations.py
- synapse/rest/client/versions.py
- tests/rest/client/test_relations.py
See [MSC3981](https://github.com/matrix-org/matrix-spec-proposals/pull/3981), this pretty much just removes flags though.
Part of #17021
> Stabliize support for MSC3981: recurse /relations

- changelog.d/17022.feature
- synapse/config/experimental.py
- synapse/rest/client/account_data.py
See [MSC4010](https://github.com/matrix-org/matrix-spec-proposals/pull/4010), but this is pretty much just removing an experimental flag.
Part of #17021
> Stabilize support for MSC4010: push rules & account data.

- changelog.d/17032.misc
- synapse/storage/databases/main/event_push_actions.py
- synapse/storage/databases/main/receipts.py
Resurrecting https://github.com/matrix-org/synapse/pull/13918.
This should reduce IOPs incurred by joining to the events table to lookup stream ordering, which happens in many receipt handling code paths. Like the previous PR I believe sufficient time has passed between the original migration in DB schema 72 and now to merge this as-is. It's highly unlikely that both the migration is still ongoing AND (active) users still have any receipts prior to that date.
In the unlikely event there is a receipt without a populated `event_stream_ordering` synapse will behave just as it does now when receipts exist for events that don't (yet): for push action calculation the receipts are just ignored.
I've removed the validation on event IDs as this is already covered here: …
> Use receipts `event_stream_ordering` instead of joins

- changelog.d/16943.bugfix
- docker/complement/conf/workers-shared-extra.yaml.j2
- scripts-dev/complement.sh
- synapse/handlers/e2e_keys.py
- synapse/rest/client/keys.py
- tests/handlers/test_e2e_keys.py
MSC3967 was updated recently to make it more robust to network failures:
> there is an existing cross-signing master key and it exactly matches the cross-signing master key provided in the request body. If there are any additional keys provided in the request (self signing key, user signing key) they MUST also match the existing keys stored on the server. In other words, the request contains no new keys. If there are new keys, UIA MUST be performed.
https://github.com/matrix-org/matrix-spec-proposals/blob/hughns/device-signing-upload-uia/proposals/3967-device-signing-upload-uia.md#proposal
This covers the case where the 200 OK is lost in transit so the client retries the upload, only to then get UIA'd.
Complement tests: https://github.com/matrix-org/complement/pull/713 - passing example …
> bugfix: make msc3967 idempotent

- .github/workflows/tests.yml
- changelog.d/17079.misc
- rust/Cargo.toml
I would like to have the new `BTreeMap` functions introduced in 1.66.0 for #17056
> Bump minimum required Rust version to 1.66.0

- Cargo.lock
- changelog.d/17081.misc
- rust/Cargo.toml
- rust/src/errors.rs
- rust/src/http.rs
- rust/src/lib.rs
Needed for #17056 
This adds functions to transform a Twisted request to the `http::Request`, and then to send back an `http::Response` through it.
It also imports the SynapseError exception so that we can throw that from Rust code directly
Example usage of this would be:
```rust
use crate::http::{http_request_from_twisted, http_response_to_twisted, HeaderMapPyExt};
fn handler(twisted_request: &PyAny) -> PyResult<()> {
let request = http_request_from_twisted(twisted_request)?;
let ua: headers::UserAgent = request.headers().typed_get_required()?;
if whatever {
return Err((crate::errors::SynapseError::new(
StatusCode::UNAUTHORIZED,
"Whatever".to_owned
"M_UNAUTHORIZED",
None,
None,
)));
}
let response = Response::new("hello".as_bytes());
http_response_to_twisted(twisted_request, response)?; …
```
> Helpers to transform Twisted requests to Rust http Requests/Responses

- changelog.d/17099.doc
- docs/message_retention_policies.md
> Clarify what part of message retention is still experimental

- rust/src/rendezvous/mod.rs
- synapse/synapse_rust/rendezvous.pyi
- tests/rest/client/test_rendezvous.py
For the attention of @anoadragon453 as this is destined for https://github.com/element-hq/synapse/pull/17056
> MSC4108 4KB maximum + 60 second TTL

- rust/src/rendezvous/mod.rs
- tests/rest/client/test_rendezvous.py
- tests/server.py
- tests/unittest.py
For attention of @anoadragon453 to land in https://github.com/element-hq/synapse/pull/17056
> Restrict MSC4108 content-type to text/plain

- changelog.d/17000.bugfix
- synapse/storage/databases/main/search.py
- tests/storage/test_room_search.py
Fixes https://github.com/element-hq/synapse/issues/16999 and https://github.com/element-hq/element-android/pull/8729 by returning the search terms as search highlights.
Note:
I'm not a python developer, and I don't know that much about synapse.  
I tested my changes on my own homeserver and I think the basic idea of using the search terms as highlights is ok, but it's very possible what I did is not the optimal way to do it.
I don't have a full python dev env available to run the linters etc, but I hope my changes are small enough that I managed to not break the code style or anything else.
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to …
> Return the search terms as search highlights for SQLite instead of nothing

- changelog.d/17071.doc
- docs/usage/configuration/config_documentation.md
> Update event_cache_size and global_factor configurations documentation

- changelog.d/17078.bugfix
- docs/workers.md
- synapse/rest/client/room.py
Keep the existing endpoint for backwards compatibility
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
> Use recommended endpoint for MSC3266 requests

- changelog.d/17084.doc
- docs/systemd-with-workers/system/matrix-synapse.service
This makes it easy to store UNIX sockets with correct permissions. Those would be located in /run/synapse which is the directory used in many examples in Synapse configuration manual. Additionally, the directory and sockets are deleted when Synapse is shut down.
(run the …
> Add RuntimeDirectory to matrix-synapse.service

- changelog.d/17077.bugfix
- synapse/storage/databases/main/transactions.py
- tests/rest/admin/test_federation.py
Fixes https://github.com/element-hq/synapse/issues/16883. Related: https://github.com/element-hq/synapse/pull/16882
This PR fixes the a bug in the [Destination Rooms Admin API](https://element-hq.github.io/synapse/latest/usage/administration/admin_api/federation.html#destination-rooms) whereby returned rooms were not filtered, even when a `destination` query parameter was supplied. A regression test has been added as well.
Missed in https://github.com/element-hq/synapse/issues/11658.
> Fix filtering of rooms when supplying the `destination` query parameter to `/_synapse/admin/v1/federation/destinations/<destination>/rooms`

- changelog.d/17127.bugfix
- synapse/federation/federation_server.py
- synapse/handlers/devicemessage.py
- tests/federation/test_federation_server.py
- tests/federation/transport/test_server.py
... when workers are unreachable, etc.
Fixes https://github.com/element-hq/synapse/issues/17117.
The general principle is just to make sure that we propagate any exceptions to the JsonResource, so that we return an error code to the sending server. That means that the sending server no longer considers the message safely sent, so it will retry later.
In the issue, Erik mentions that an alternative solution would be to persist the to-device messages into a table so that they can be retried. This might be an improvement for performance, but even if we did that, we still need this mechanism, since we might be unable to reach the database. So, if we want to do that, it can be a later follow-up.
> Ensure that incoming to-device messages are not dropped

- changelog.d/17131.misc
- poetry.lock
This PR updates the `tornado` dependency from 6.2 to 6.4. Let's see if CI passes!
> Update tornado 6.2 -> 6.4

- changelog.d/17104.feature
- docker/complement/conf/workers-shared-extra.yaml.j2
- rust/src/events/internal_metadata.rs
- synapse/api/constants.py
- synapse/config/experimental.py
- synapse/events/utils.py
- synapse/handlers/admin.py
- synapse/handlers/events.py
- synapse/handlers/initial_sync.py
- synapse/handlers/pagination.py
- synapse/handlers/relations.py
- synapse/handlers/room.py
- synapse/handlers/search.py
- synapse/handlers/sync.py
- synapse/notifier.py
- synapse/push/mailer.py
- synapse/visibility.py
- tests/events/test_utils.py
- tests/rest/client/test_retention.py
- tests/test_visibility.py
Add membership metadata to each event returned to the client, per MSC4115
> Add support for MSC4115

- changelog.d/17120.bugfix
- docs/sso_mapping_providers.md
- synapse/handlers/sso.py
- synapse/rest/synapse/client/pick_username.py
- tests/rest/client/test_login.py
This change will apply the `email` & `picture` provided by OIDC to the new user account when registering a new user via OIDC. If the user is directed to the account details form, this change makes sure they have been selected before applying them, otherwise they are omitted. In particular, this change ensures the values are carried through when Synapse has consent configured, and the redirect to the consent form/s are followed.
I have tested everything manually. Including: 
- with/without consent configured
- allowing/not allowing the use of email/avatar (via  `sso_auth_account_details.html`)
- with/without automatic account detail population (by un/commenting the `localpart_template` option in synapse config).
- Be a short description of your change which makes sense to users. "Fixed a …
> Apply user `email` & `picture` during OIDC registration if present & selected

- changelog.d/17137.feature
- scripts-dev/complement.sh
Follow-up to #17137 and https://github.com/matrix-org/complement/pull/722
> Enable complement tests for MSC4115 support

- changelog.d/17105.misc
- docker/complement/conf/workers-shared-extra.yaml.j2
This is an alternative to https://github.com/matrix-org/matrix-rust-sdk/issues/3340 where we don't need to change our CI setup too much in the Rust SDK repository, and still can test MSC3266.
> synapse complement image: hardcode enabling msc3266

- changelog.d/17152.bugfix
- synapse/util/caches/stream_change_cache.py
Annoyingly mypy didn't pick up this typo.
> Fix bug where `StreamChangeCache` would not respect cache factors

- changelog.d/17130.misc
- synapse/util/caches/stream_change_cache.py
- tests/util/test_stream_change_cache.py
When there have been lots of changes compared with the number of entities, we can do a fast(er) path.
Locally I ran some benchmarking, and the comparison seems to give the best determination of which method we use.
> Add optimisation to `StreamChangeCache`

- changelog.d/17139.doc
- docs/admin_api/user_admin_api.md
If the login method is OIDC then the external id provider must be prefixed with 'oidc-', which was not mentioned before.
> Add note about external_ids for User Admin API in documentation

- changelog.d/17150.doc
- docs/usage/configuration/config_documentation.md
Link to the `/createRoom` preset docs and note how they behave in the same manner when providing the preset name to the `autocreate_auto_join_room_preset` config option.
Off the back of an internal conversation asking for clarity around this behaviour.
> Note preset behaviour in `autocreate_auto_join_room_preset` docs

- Cargo.lock
- changelog.d/17162.misc
- rust/Cargo.toml
- rust/src/acl/mod.rs
- rust/src/events/internal_metadata.rs
- rust/src/events/mod.rs
- rust/src/http.rs
- rust/src/lib.rs
- rust/src/push/mod.rs
- rust/src/rendezvous/mod.rs
This version change requires a migration to a new API. See https://pyo3.rs/v0.21.2/migration#from-020-to-021
This will fix the annoying warnings added when using the recent rust nightly:
> warning: non-local `impl` definition, they should be avoided as they go against expectation
> Update PyO3 to 0.21

- changelog.d/17145.bugfix
- synapse/federation/transport/server/_base.py
- tests/federation/transport/server/test__base.py
Fix #1350 by adding support for optional whitespace around `,`.
Additionally, 
- used `\s` which is more lax than the spec since `OWS` is defined as `*( SP / HTAB )`
- Added the `X-Matrix` part to the regex ` ^X-Matrix\s+`  to make more clear what it's doing. Added it as insensitive to lower probability of issues, but since it was not checking the `X-Matrix` part before it could create issues. 
- On the whitespace handling of this part replaced ` +` with `\s+` since the parsing appear to be more lax than the spec (which if I understand correctly mandate only one space, cf `1*SP`)
Will of course remove it if you believe it should not be included.
> Optional whitespace support in Authorization (#1350)

- changelog.d/17171.doc
- docs/usage/administration/admin_faq.md
- docs/workers.md
> Update docs to bump libjemalloc version on latest debian; correct "push_rules" stream name

- changelog.d/17177.bugfix
- synapse/storage/databases/main/room.py
If room publication is disabled then creating public rooms on workers would not work.
Introduced in #16811.
Stack trace:
```
AttributeError: 'GenericWorkerStore' object has no attribute 'set_room_is_public'
File "synapse/http/server.py", line 332, in _async_render_wrapper
callback_return = await self._async_render(request)
File "synapse/http/server.py", line 544, in _async_render
callback_return = await raw_callback_return
File "synapse/rest/client/room.py", line 171, in on_POST
return await self._do(request, requester)
File "synapse/rest/client/room.py", line 176, in _do
room_id, _, _ = await self._room_creation_handler.create_room(
File "synapse/handlers/room.py", line 921, in create_room
await self.store.set_room_is_public(room_id, False)
```
> Fix bug with creating public rooms on workers

- changelog.d/17184.bugfix
- synapse/storage/databases/main/room.py
See #17177.
I'm an idiot and moved them to the wrong store :facepalm:
> Actually fix public rooms

- changelog.d/17199.feature
- docs/usage/configuration/config_documentation.md
This commit fixes the request path in the `federation_whitelist_endpoint_enabled` config option.
The path was changed towards the tail end of development in https://github.com/element-hq/synapse/pull/16848. Thus updating it in the documentation was missed.
> Fix request path for `federation_whitelist_endpoint_enabled` option in documentation

- changelog.d/17200.misc
- synapse/handlers/sync.py
- synapse/rest/client/sync.py
- tests/events/test_presence_router.py
- tests/handlers/test_sync.py
Refactor Sync handler to be able to be able to return different sync responses (`SyncVersion`). Preparation to be able support sync v2 and a new Sliding Sync `/sync/e2ee` endpoint which returns a subset of sync v2.
Split upon request: https://github.com/element-hq/synapse/pull/17167#discussion_r1601497279
Split from https://github.com/element-hq/synapse/pull/17167 where we will add `SyncVersion.E2EE_SYNC` and a new type of sync response.
- …
> Refactor Sync handler to be able to return different sync responses (`SyncVersion`)

- changelog.d/17142.bugfix
- synapse/handlers/sync.py
- tests/handlers/test_sync.py
Fixes #16987
Some old accounts seem to have an entry in global account data table for push rules, which we should ignore
> Fix bug where push rules would be empty in `/sync`

- changelog.d/17200.misc
- changelog.d/17201.misc
- synapse/handlers/sync.py
- synapse/rest/client/sync.py
- tests/events/test_presence_router.py
- tests/handlers/test_sync.py
Removed `request_key` from the `SyncConfig` (moved outside as its own function parameter) so it doesn't have to flow into `_generate_sync_entry_for_xxx` methods. This way we can separate the concerns of caching from generating the response and reuse the `_generate_sync_entry_for_xxx` functions as we see fit. Plus caching doesn't really have anything to do with the config of sync.
Split from https://github.com/element-hq/synapse/pull/17167
Spawning from https://github.com/element-hq/synapse/pull/17167#discussion_r1601497279
- Waiting on https://github.com/element-hq/synapse/pull/17200 to merge first
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to …
> Removed `request_key` from the `SyncConfig` (moved outside as its own function parameter)

- changelog.d/17203.misc
- synapse/handlers/sync.py
Rename to be obvious: `joined_rooms` -> `joined_room_ids`
Split out from https://github.com/element-hq/synapse/pull/17167
> Rename to be obvious: `joined_rooms` -> `joined_room_ids`

- changelog.d/17208.misc
- synapse/handlers/sync.py
Fix `joined_rooms`/`joined_room_ids` usage
This change was introduced in https://github.com/element-hq/synapse/pull/17203
But then https://github.com/element-hq/synapse/pull/17207 was reverted which brought back usage of `joined_rooms` that needed to be updated. Wasn't caught because `develop` wasn't up to date before merging.
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your …
> Fix `joined_rooms`/`joined_room_ids` usage

- changelog.d/17202.misc
- synapse/handlers/sync.py
Refactor `SyncResultBuilder` assembly to its own function. We will re-use `get_sync_result_builder(...)` in https://github.com/element-hq/synapse/pull/17167.
Split out from https://github.com/element-hq/synapse/pull/17167
(run the [linters](https://element-hq.github.io/synapse/latest/development/con …
> Refactor `SyncResultBuilder` assembly to its own function

- changelog.d/17058.doc
- docs/workers.md
Knocking Endpoints was missing for federaded Worker
* [X ] Pull request is based on the develop branch
> Federated Knocking Endpoints added (missing in Docu)

- changelog.d/17210.misc
- synapse/api/ratelimiting.py
- tests/api/test_ratelimiting.py
- tests/handlers/test_federation.py
- tests/handlers/test_room_member.py
- tests/unittest.py
This helps prevent clients from "tight-looping" retrying their request.
> Add a short sleep if the request is rate-limited

- changelog.d/17219.feature
- synapse/util/task_scheduler.py
The log format is the same as the request log format, except:
- fields that are specific to HTTP requests have been removed
- the task's params are included at the end of the log line.
These log lines are emitted:
- when the task function finishes — both completion and failure (and I suppose it is possible for a task to become schedulable again?)
- every 5 minutes whilst it is running
Closes #17217.
> Add logging to tasks managed by the task scheduler, showing CPU and database usage.

- changelog.d/17213.feature
- synapse/config/experimental.py
- synapse/media/thumbnailer.py
- synapse/rest/client/media.py
- synapse/rest/media/thumbnail_resource.py
- tests/media/test_media_storage.py
- tests/rest/client/test_media.py
[MSC3916](https://github.com/matrix-org/matrix-spec-proposals/blob/rav/authentication-for-media/proposals/3916-authentication-for-media.md) adds new media endpoints under `_matrix/client`. This PR adds the `/preview_url`, `/config`, and `/thumbnail` endpoints. `/download` will be added in a follow-up PR once the work for the federation `/download` endpoint is complete (see https://github.com/element-hq/synapse/pull/17172).
Should be reviewable commit-by-commit.
> Support MSC3916 by adding unstable media endpoints to `_matrix/client`

- changelog.d/17239.misc
- synapse/media/media_repository.py
- synapse/media/media_storage.py
- synapse/media/url_previewer.py
- tests/rest/client/test_media.py
- tests/rest/media/test_domain_blocking.py
When a module rejects a piece of media we end up trying to close the same logging context twice.
Instead of fixing the existing code we refactor to use an async context manager, which is easier to write correctly.
> Fix slipped logging context when media rejected

- changelog.d/17241.bugfix
- synapse/handlers/e2e_keys.py
Currently this causes one of then to 500.
<details>
<summary>Stack trace</summary>
```
UniqueViolation: duplicate key value violates unique constraint "e2e_one_time_keys_json_uniqueness"
DETAIL:  Key (user_id, device_id, algorithm, key_id)=(xxx, xxx, xxx, xxx) already exists.
File "synapse/http/server.py", line 332, in _async_render_wrapper
callback_return = await self._async_render(request)
File "synapse/http/server.py", line 544, in _async_render
callback_return = await raw_callback_return
File "synapse/replication/http/_base.py", line 433, in _check_auth_and_handle
code, response = await self._handle_request(request, content, **kwargs)
File "synapse/replication/http/devices.py", line 161, in _handle_request
results = await self.e2e_keys_handler.upload_keys_for_user(
File …
```
> Handle duplicate OTK uploads racing

- changelog.d/17240.bugfix
- synapse/handlers/devicemessage.py
Currently sending a to-device message to a user ID with a dodgy destination is accepted, but then ends up spamming the logs when we try and send to the destination.
An alternative would be to reject the request, but I'm slightly nervous that could break things.
> Ignore attempts to send to-device messages to bad users

- changelog.d/17238.misc
- docs/postgres.md
- synapse/storage/engines/postgres.py
We relax this as there are use cases where this is safe, though it is still highly recommended that people avoid using it.
> Change allow_unsafe_locale to also apply on new databases

- changelog.d/17083.misc
- synapse/handlers/relations.py
- synapse/storage/databases/main/cache.py
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/databases/main/relations.py
This is a tree cache already, so may as well move the room ID to the front and use that
> Don't invalidate all `get_relations_for_event` on history purge

- changelog.d/17226.misc
- synapse/storage/database.py
- synapse/storage/databases/main/account_data.py
- synapse/storage/databases/main/deviceinbox.py
- synapse/storage/databases/main/events_worker.py
- synapse/storage/databases/main/presence.py
- synapse/storage/databases/main/receipts.py
- synapse/storage/databases/main/room.py
- synapse/storage/util/id_generators.py
- tests/storage/test_id_generators.py
There is a problem with `StreamIdGenerator` where it can go backwards over restarts when a stream ID is requested but then not inserted into the DB. This is problematic if we want to land #17215, and is generally a potential cause for all sorts of nastiness.
Instead of trying to fix `StreamIdGenerator`, we may as well move to `MultiWriterIdGenerator` that does not suffer from this problem (the latest positions are stored in `stream_positions` table). This involves adding SQLite support to the class.
This only changes id generators that were already using `MultiWriterIdGenerator` under postgres, a separate PR will move the rest of the uses of `StreamIdGenerator` over.
Reviewable commit-by-commit.
> Move towards using `MultiWriterIdGenerator` everywhere

- changelog.d/17246.misc
- synapse/media/media_repository.py
- synapse/media/media_storage.py
Fixes up #17239
We need to keep the spam check within the `try/except` block. Also makes it so that we don't enter the top span twice.
Also also ensures that we get the right thumbnail length.
> Ensure we delete media if we reject due to spam check

- changelog.d/17242.misc
- synapse/storage/databases/main/deviceinbox.py
- synapse/storage/schema/main/delta/85/04_cleanup_device_federation_outbox.sql
We started ensuring we only insert valid destinations: https://github.com/element-hq/synapse/pull/17240
> Clean out invalid destinations from outbox

- changelog.d/17251.bugfix
- synapse/app/_base.py
This was broken by the sentry 2.0 upgrade
Broke in v1.108.0
> Fix sentry default tags

- changelog.d/17252.bugfix
- synapse/handlers/typing.py
- tests/handlers/test_typing.py
This can happen on restarts of the service, due to old rooms being pruned.
> Fix bug where typing replication breaks

- changelog.d/17254.bugfix
- synapse/storage/databases/main/user_directory.py
- tests/handlers/test_user_directory.py
- tests/storage/test_user_directory.py
> Handle hyphens in user dir search porperly

- changelog.d/17273.misc
- synapse/handlers/e2e_keys.py
It's just a waste of time if we won't even query the remote host as its marked as down.
> Don't try and resync devices for down hosts

- changelog.d/17271.misc
- synapse/handlers/e2e_keys.py
- synapse/rest/client/keys.py
And fallback keys uploads. Only device keys need handling on master
> Handle OTK uploads off master

- changelog.d/17266.misc
- synapse/handlers/e2e_room_keys.py
Fixes: #17013 
Add logging for whether room keys are replaced \
This is motivated by the Crypto team who need to diagnose crypto issues.
The existing opentracing logging is not enough because it is not enabled
for all users.
> Add debug logging for when room keys are uploaded, including whether they are replacing other room keys.

- changelog.d/17272.bugfix
- synapse/visibility.py
Wrong retention policy being used when filtering events.
Fix loop var being used outside block.
Before this change, we were always using the last room_id's retention policy for all events being filtered.
I found this bug with the [new lint rule, `ControlVarUsedAfterBlockViolation` `WPS441`](https://github.com/astral-sh/ruff/pull/11769), that I re-implemented in `ruff`. Shout-out to @reivilibre for all the help in the beginning! 
- Feel free …
> Wrong retention policy being used when filtering events (lint `ControlVarUsedAfterBlockViolation` `WPS441`)

- changelog.d/17296.feature
- synapse/rest/client/reporting.py
This clarifies in the comments that the MSC is being used in matrix.org
See #17270
> Clarify that MSC4151 is enabled on matrix.org

- changelog.d/17297.misc
- poetry.lock
- tests/push/test_email.py
- tests/rest/client/test_account.py
Supersedes https://github.com/element-hq/synapse/pull/17286.
This PR inserts assertions into test code to convince mypy that we're correctly using poorly-typed standard library methods.
> Bump `mypy` from 1.8.0 to 1.9.0

- changelog.d/17295.bugfix
- synapse/storage/databases/main/stream.py
- tests/storage/test_stream.py
*Found while working on Sliding Sync and split out from https://github.com/element-hq/synapse/pull/17293*
---
Fix `get_last_event_in_room_before_stream_ordering(...)` finding the wrong last event.
PR where this was introduced: https://github.com/matrix-org/synapse/pull/14817
`get_last_event_in_room_before_stream_ordering(...)` is used in Sync v2 in a lot of different state calculations.
`get_last_event_in_room_before_stream_ordering(...)`  is also used in `/rooms/{roomId}/members` 
- End with either a period (.) or an exclamation …
> Fix `get_last_event_in_room_before_stream_ordering(...)` finding the wrong last event

- changelog.d/17300.misc
- rust/src/events/internal_metadata.rs
- synapse/events/utils.py
- synapse/handlers/message.py
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/events_worker.py
- synapse/synapse_rust/events.pyi
- tests/events/test_utils.py
- tests/replication/storage/test_events.py
- tests/storage/test_event_chain.py
Add `event.internal_metadata.instance_name` (the worker instance that persisted the event) to go alongside the existing `event.internal_metadata.stream_ordering`.
`instance_name` is useful to properly compare and query for events with a token since you need to compare both the `stream_ordering` and `instance_name` against the vector clock/`instance_map` in the `RoomStreamToken`.
This is pre-requisite work and may be used in https://github.com/element-hq/synapse/pull/17293
Adding `event.internal_metadata.instance_name` was first mentioned in the initial Sliding Sync PR while pairing with @erikjohnston, see https://github.com/element-hq/synapse/pull/17187/commits/09609cb0dbca3a4cfd9fbf90cc962e765ec469c0#diff-5cd773fb307aa754bd3948871ba118b1ef0303f4d72d42a2d21e38242bf4e096R405-R410
- Be a …
> Add `event.internal_metadata.instance_name`

- changelog.d/17301.bugfix
- synapse/handlers/sliding_sync.py
- tests/handlers/test_sliding_sync.py
Fix `newly_left` rooms not appearing if we returned early when `membership_snapshot_token.is_before_or_eq(to_token.room_key)`. 
Introduced in https://github.com/element-hq/synapse/pull/17187 (part of Sliding Sync)
The tests didn't catch it because they had a small typo in it `room_id1` vs `room_id2`.
Found while working on https://github.com/element-hq/synapse/pull/17293
- Feel free to credit yourself, by adding a sentence "Contributed by …
> Fix `newly_left` rooms not appearing if we returned early (Sliding Sync)

- .github/workflows/release-artifacts.yml
- changelog.d/17319.misc
This changes the release artefacts workflow to use `macos-12` runners instead of `macos-11`, as the latter will be fully deprecated in a few days.
I also had to update `cibuildwheel` to a newer version, as it would not 'repair' the macOS wheels correctly
The difference is that now instead of outputting a macOS 11+ compatible wheel, we output a macOS 12+ compatible one. This is fine, as macOS 11 is considered EOL since September 2023.
We can also expect that macOS 12 will be considered EOL in September 2024, as Apple usually supports the last 3 macOS version, and macOS 15 is scheduled to be released around that time.
The last commit on that PR should be removed before merging, as it is there only to have all wheels built like a release on a PR.
> Switch to macOS 12 runners to fix building of wheels for macOS

- changelog.d/17308.doc
- docs/usage/configuration/config_documentation.md
We tried to configure rooms `exclude_rooms_from_sync`. If we do not quote we get an error.
The example should be valid.
> fix missing quotes for exclude_rooms_from_sync

- changelog.d/17322.feature
- synapse/config/experimental.py
- synapse/rest/client/knock.py
- synapse/rest/client/room.py
This adds support for the `via` query parameter from https://github.com/matrix-org/matrix-spec-proposals/pull/4156.
> Add support for via query parameter from MSC4156

- changelog.d/17283.bugfix
- synapse/rest/client/notifications.py
- synapse/storage/databases/main/event_push_actions.py
- tests/module_api/test_api.py
- tests/rest/client/test_notifications.py
Fixes https://github.com/element-hq/synapse/issues/16921
While this is classed as a 'string' in the spec, the provided value must be an integer in order for pagination to work. Thus any non-integer value must be rejected.
A couple tests are also added: one general one for pagination that was missing (`test_pagination_of_notifications`), and a regression test for this fix (`test_parameters`). A helper function (`_request_notifications`) was also added, and used in the existing test code. I also moved the creation of the test users and room into the `prepare` function as it's needed by multiple tests anyway.
> Require the 'from' parameter for `/notifications` be an integer

- changelog.d/17291.misc
- synapse/storage/controllers/persist_events.py
- synapse/storage/databases/main/events.py
- tests/storage/test_event_chain.py
- tests/storage/test_event_federation.py
We calculate the auth chain links outside of the main persist event transaction to ensure that we do not block other event sending during the calculation.
> Handle large chain calc better

- changelog.d/17198.misc
- docker/conf/homeserver.yaml
This value has been ignored since #5782, so there's no reason to keep it around in the docker homeserver.yaml.
> Remove `expire_access_token` from Docker configuration

- README.rst
- changelog.d/17324.misc
This PR updates the Synapse README to make it clearer that this is an Element-branded product and that people are not required, but have the option to, pay Element for enterprise features and support.
Such support is critical to continued development of Synapse.
No new restrictions are in place; this PR is purely to tell people about the existing Element Server Suite product, should they wish to get enterprise support instead of going it on their own.
This commit also contains some aesthetic changes and a fix to the shield icon that points to the community support room, which has been broken for a long time. The breakage is due to it taking too long for matrix.org to calculate the membership for that room on the endpoint that shields.io requests. So it's been swapped out for a static …
> Update the README with Element branding and a few fixes

- changelog.d/17276.feature
- docs/admin_api/rooms.md
- synapse/rest/admin/rooms.py
- synapse/storage/databases/main/room.py
- tests/rest/admin/test_room.py
Signed-off-by: Alexander Fechler <alexander.fechler@bwi.de>
> Filter added to Admin-API GET /rooms

- changelog.d/17304.feature
- debian/changelog
- debian/register_new_matrix_user.ronn
- synapse/_scripts/register_new_matrix_user.py
Depends on https://github.com/element-hq/synapse/pull/17294
Release notes + docs will follow once we agree on the implementation.
> register-new-matrix-user: add a flag to ignore already existing users

- changelog.d/17331.misc
- synapse/rest/client/sync.py
- tests/rest/client/test_sync.py
As the API is slightly incompatible.
> Register sliding sync under a different path

- changelog.d/17291.misc
- synapse/storage/controllers/persist_events.py
- synapse/storage/databases/main/events.py
- tests/storage/test_event_chain.py
- tests/storage/test_event_federation.py
This reverts commit bdf82efea505c488953b46eb681b5a63c4e9655d  (#17291)
This seems to have stopped persisting auth chains for new events, and so is causing state res to fall back to the slow methods
> Revert "Handle large chain calc better (#17291)"

- changelog.d/17339.misc
- synapse/http/servlet.py
- synapse/rest/admin/federation.py
- synapse/rest/admin/media.py
- synapse/rest/admin/statistics.py
- synapse/rest/admin/users.py
- synapse/rest/client/room.py
- synapse/streams/config.py
During https://github.com/element-hq/synapse/pull/16920, we seem to have inadvertently disallowed negative integers in `parse_integer` by default. This was contrary to the `parse_integer` documentation.
Surprisingly, nothing really broke, which indicates that things mostly do expect positive integers. Running an ast-grep query confirms it:
```
❯ ast-grep run --pattern 'parse_integer($A, $PARAM, $$$)' --json=pretty | jq -r '.[].metaVariables.single.PARAM.text' | sort -u
"before_ts"
"from"
"from_token"
"from_ts"
"height"
"limit"
"size_gt"
"timeout"
"timeout_ms"
"ts"
"upto_token"
"width"
```
As can be seen, these boil down to timestamps, limits, timeouts, sizes, etc, none of which really make sense to be negative. So it seems we've inadvertently stumbled into
This PR:
- Brings the docs into …
> Tidy up integer parsing

- changelog.d/17336.bugfix
- synapse/push/mailer.py
Fix room `type` typo in mailer
Correct event content field is `EventContentFields.ROOM_TYPE` (`type`) :white_check_mark: , not `room_type` :x:
Spec: https://spec.matrix.org/v1.10/client-server-api/#mroomcreate
> ### `m.room.create`
> 
> Name | Type | Description
> --- | --- | ---
> `creator` | `string` | The `user_id` of the room creator. Required for, and only present in, room versions 1 - 10. Starting with room version 11 the event `sender` should be used instead.
> `m.federate` | `boolean` | Whether users on other servers can join this room. Defaults to `true` if key does not exist.
> `predecessor` | `Previous Room` | A reference to the room this room replaces, if the previous room was upgraded.
> `room_version` | `string` | The version of the room. Defaults to "1" if the key does not …
> Fix room `type` typo in mailer

- changelog.d/17347.doc
- docs/usage/configuration/config_documentation.md
A simple change to update the docs where default values were missing.
> Add default values for rc_invites per_issuer to docs

- changelog.d/17335.feature
- synapse/handlers/sliding_sync.py
- tests/handlers/test_sliding_sync.py
- tests/rest/client/test_sync.py
Add `is_invite` filtering to Sliding Sync `/sync`
Based on [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575): Sliding Sync
> Add `is_invite` filtering to Sliding Sync `/sync`

- changelog.d/17358.misc
- synapse/storage/databases/main/devices.py
Fixes up #17333, where we failed to actually send less data (the `DISTINCT` didn't work due to `stream_id` being different). 
We fix this by making it so that every device list outbound poke for a given user ID has the same stream ID. We can't change the query to only return e.g. max stream ID as the receivers look up the destinations to send to by doing `SELECT WHERE stream_id = ?`
> Limit amount of replication we send

- changelog.d/17350.feature
- synapse/federation/transport/server/__init__.py
- synapse/federation/transport/server/_base.py
- synapse/federation/transport/server/federation.py
- synapse/media/_base.py
- synapse/media/media_repository.py
- synapse/media/media_storage.py
- tests/federation/test_federation_media.py
- tests/server.py
This PR re-introduces the federation `/download` endpoint outlined in [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/blob/rav/authentication-for-media/proposals/3916-authentication-for-media.md) - the original [PR](https://github.com/element-hq/synapse/pull/17172) for this was reverted in https://github.com/element-hq/synapse/pull/17325 due to an incompatibility with 3rd party storage providers.
This PR implements the multipart/mixed response by wrapping and transforming the file stream from the storage provider, thus eliminating the incompatibility.
> Re-introduce federation /download endpoint

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- changelog.d/17341.doc
- docs/welcome_and_overview.md
Removes stale references to Matrix.org's SDP and replace it with Element's.
> Fix outdated Security Disclosure Policy references

- README.rst
- changelog.d/17329.doc
With the top-level header, the auto-generated TOC is pretty ugly.
We could manually write a TOC, but we'd need to keep it up to date.
GitHub generates a TOC already - just hit the Outline button:
~~I propose to just remove it.~~ Let's fix it: https://github.com/element-hq/synapse/pull/17329#issuecomment-2182617839
(Note that this is probably the only thing holding us back from converting the README to markdown - but that would be a separate PR.)
> Fixes to the table of contents in the README

- README.rst
- changelog.d/17363.misc
As per https://github.com/sphinx-doc/sphinx/issues/3921#issuecomment-315581557, we need double underscores.
Running `rst2html README.rst > /dev/null` found some more warnings.
> Fix uploading packages to PyPi

- changelog.d/17362.bugfix
- synapse/storage/databases/main/deviceinbox.py
Fix bug where we don't get new to-device from remote if they resent a message we've already persisted and have recorded in the DB twice.
`device_federation_inbox` table doesn't have a unique index, and so we can race and store an entry in there twice. If we do so then `simple_select_one_txn` will throw an error due to the query returning more than one row. We should add an unique index, but it doesn't really matter so lets just handle the case of multiple rows correctly for now.
> Handle multiple rows device inbox

- .github/workflows/tests.yml
- changelog.d/17367.misc
Follow up to https://github.com/element-hq/synapse/pull/17363, so we can detect issues with the RST file early on.
> Use rstcheck to "lint" the README

- changelog.d/17356.doc
- docs/usage/configuration/config_documentation.md
> Clarify `url_preview_url_blacklist` is a usability feature

- changelog.d/17371.misc
- synapse/federation/sender/per_destination_queue.py
- tests/federation/test_federation_sender.py
> Limit size of presence EDUs

- changelog.d/17390.misc
- docker/build_debian.sh
If we leave the `.so` in place it causes the tests to fail, as it gets picked up (instead of the newly built .so) and so fails with mismatched GLIBC errors.
> Fix building debian packages on non-clean checkouts

- changelog.d/17318.misc
- scripts-dev/release.py
We got bitten a bit during the v1.109 release, where even though our CI would pick up any release-vXXX branch on complement, we don't automatically create them in the complement repo.
This adds this logic to the release script.
> Make the release script create a release branch for Complement as well

- changelog.d/17400.feature
- synapse/handlers/deactivate_account.py
- tests/handlers/test_deactivate_account.py
This can help ensure that the rooms are eventually purged if the other local users also forget them. Synapse already clears some of the room information as part of the `_background_remove_left_rooms` background task, but this doesn't catch `events`, `event_json`, etc.
> Upon deactivation, forget all of the user's rooms

- changelog.d/17392.misc
- docs/admin_api/experimental_features.md
- synapse/rest/admin/experimental_features.py
- synapse/rest/client/pusher.py
- synapse/rest/client/versions.py
- synapse/storage/databases/main/experimental_features.py
- tests/push/test_http.py
- tests/rest/admin/test_admin.py
Follows on from @H-Shay's great work at https://github.com/matrix-org/synapse/pull/15344 and MSC4026.
Also enables its use for MSC3881, mainly as an easy but concrete example of how to use it.
> Finish up work to allow per-user feature flags

- changelog.d/17393.misc
- docs/admin_api/experimental_features.md
- synapse/api/auth/__init__.py
- synapse/api/auth/internal.py
- synapse/api/auth/msc3861_delegated.py
- synapse/rest/admin/experimental_features.py
- synapse/rest/client/sync.py
> Allow enabling sliding sync per-user

- changelog.d/17388.feature
- synapse/config/experimental.py
- synapse/federation/transport/server/__init__.py
- synapse/federation/transport/server/_base.py
- synapse/federation/transport/server/federation.py
- synapse/media/media_repository.py
- synapse/media/thumbnailer.py
- synapse/rest/client/media.py
- synapse/rest/media/thumbnail_resource.py
- tests/federation/test_federation_media.py
- tests/media/test_media_storage.py
- tests/rest/client/test_media.py
[MSC3916](https://github.com/matrix-org/matrix-spec-proposals/pull/3916)  added the endpoints `_matrix/federation/v1/media/thumbnail`  and the authenticated `_matrix/client/v1/media/thumbnail`. 
This PR implements those endpoints, along with stabilizing `_matrix/client/v1/media/config` and `_matrix/client/v1/media/preview_url`.
Should be reviewable commit-by-commit.
Complement tests are at https://github.com/matrix-org/complement/pull/728
> Support MSC3916 by adding a federation /thumbnail endpoint and authenticated `_matrix/client/v1/media/thumbnail` endpoint

- changelog.d/17406.misc
- synapse/api/auth/msc3861_delegated.py
- synapse/config/experimental.py
This makes it easier to go through an internal endpoint instead of the public facing URL when introspecting tokens, reducing latency.
> MSC3861: allow overriding the introspection endpoint

- changelog.d/17398.bugfix
- synapse/storage/_base.py
- synapse/storage/databases/main/cache.py
- synapse/storage/databases/main/events_worker.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/databases/main/stream.py
- tests/handlers/test_sync.py
- tests/replication/storage/test_events.py
We don't necessarily have `instance_name` for old events (before we support multiple event persisters). We treat those as if the `instance_name` was "master".
> Fix bug in sliding sync when using old DB.

- changelog.d/17410.misc
- synapse/app/generic_worker.py
- synapse/rest/client/versions.py
We need it to work on workers and allow guest access.
Broke by #17392
> Fix `/versions` requests

- changelog.d/17422.misc
- docker/configure_workers_and_start.py
Missed in https://github.com/element-hq/synapse/pull/17350.
> Route auth'd fed media requests to media repo in Complement tests

- changelog.d/17421.doc
- docs/upgrade.md
- docs/workers.md
Media workers can handle the new auth'd media federation endpoints as well.
The new endpoints are:
* [`GET /_matrix/federation/v1/media/download/{mediaId}`](https://spec.matrix.org/v1.11/server-server-api/#get_matrixfederationv1mediadownloadmediaid)
* [`GET /_matrix/federation/v1/media/thumbnail/{mediaId}`](https://spec.matrix.org/v1.11/server-server-api/#get_matrixfederationv1mediathumbnailmediaid)
> Note the new federated media worker endpoints in the worker docs & upgrade notes

- changelog.d/17418.feature
- synapse/handlers/sliding_sync.py
- tests/rest/client/test_sync.py
Add `rooms` `name` and `avatar` to Sliding Sync `/sync`
Based on [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575): Sliding Sync
> Add `rooms` `name` and `avatar` to Sliding Sync `/sync`

- changelog.d/17416.feature
- synapse/handlers/sliding_sync.py
- synapse/rest/client/sync.py
- synapse/types/handlers/__init__.py
- synapse/types/rest/client/__init__.py
- tests/rest/client/test_sync.py
> Handle to-device extensions to Sliding Sync

- docker/Dockerfile
- docker/Dockerfile-dhvirtualenv
Docker build is now warning about this:
[+] Building 56.1s (36/36) FINISHED
=> CACHED [synapse-worker-sender1 internal] load git source https://github.com/element-hq/synapse.git
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 30)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 90)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 30)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 90)
- End with either a period (.) or an …
> Use consistent casing between FROM and AS

- changelog.d/17423.doc
- docs/setup/forward_proxy.md
- docs/setup/installation.md
Added RHEL/Rocky install instructions (PyPI). Instructions cover versions 8 and 9 which are the only supported ones - except for RHEL7 which is now on extended life cycle support …
> Add Red Hat Enterprise Linux and Rocky Linux installation instructions

- changelog.d/17426.misc
- synapse/api/ratelimiting.py
This looks like a copy/paste error: the function doesn't reject anything, but instead allows the action count to go through regardless. The remainder of the function's documentation appears correct.
> Fix docs on `record_action` to clarify the actions are applied

- changelog.d/17424.misc
- synapse/app/homeserver.py
- synapse/config/repository.py
- synapse/config/server.py
This removes the `enable_media_repo` attribute on the server config in favour of always using the `can_load_media_repo` in the media config. This should avoid issues like in #17420 in the future
> Make sure we use the right logic for enabling the media repo.

- changelog.d/17438.bugfix
- synapse/handlers/sliding_sync.py
- synapse/types/__init__.py
- tests/test_types.py
This is because we serialized the token wrong if the instance map
contained entries from before the minimum token.
> Fix bug where sync could get stuck when using workers

- changelog.d/17449.bugfix
- tests/server.py
This fell out of the authenticated media work - this bit of code masked a bug but does not break anything when removed, so probably should be removed.
> Remove unnecessary call to resume producing in fake channel

- changelog.d/17439.bugfix
- synapse/http/matrixfederationclient.py
- tests/media/test_media_storage.py
- tests/rest/client/test_media.py
Prior to this PR, remote downloads which did not provide a `content-length` were decremented from the remote download ratelimiter at the max allowable size, leading to excessive ratelimiting - see https://github.com/element-hq/synapse/issues/17394.
This PR adds a linearizer to limit concurrent remote downloads to 6 per IP address, and decrements remote downloads without a `content-length` from the ratelimiter *after* the download is complete and the response length is known. 
Also adds logic to ensure that responses with a known length respect the `max_download_size`.
> Handle remote download responses with `UNKNOWN_LENGTH` more gracefully

- changelog.d/17435.bugfix
- synapse/storage/databases/main/roommember.py
- tests/rest/client/test_sync.py
- tests/storage/test_roommember.py
Order `heroes` by `stream_ordering` as the spec mentions. The spec specifically mentions `stream_ordering` but that's a Synapse specific concept. In any case, the essence of the spec is basically the first 5 members of the room which `stream_ordering` accomplishes.
Split off from https://github.com/element-hq/synapse/pull/17419#discussion_r1671342794
> This should be the first 5 members of the room, **ordered by stream ordering**, which are joined or invited. The list must never include the client’s own user ID. When no joined or invited members are available, this should consist of the banned and left users.
>
> *-- https://spec.matrix.org/v1.10/client-server-api/#_matrixclientv3sync_roomsummary*
Related to https://github.com/matrix-org/matrix-spec/issues/1334
It's already a `FIXME` …
> Order `heroes` by `stream_ordering` (as spec'ed)

- changelog.d/17453.misc
- synapse/handlers/sliding_sync.py
Add `m.room.create` to default bump event types
This probably helps when no messages have been sent in the room and it was just created.
> Add `m.room.create` to default bump event types

- poetry.lock
Reverts element-hq/synapse#17448
We hit a bug when deploying with synctl:
```
Traceback (most recent call last):
File "/home/synapse/env-python311/bin/synctl", line 33, in <module>
sys.exit(load_entry_point('matrix-synapse', 'console_scripts', 'synctl')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/synapse/env-python311/bin/synctl", line 25, in importlib_load_entry_point
return next(matches).load()
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
module = import_module(match.group('module'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level) …
```
> Revert "Bump setuptools from 67.6.0 to 70.0.0"

- changelog.d/17451.doc
- docs/usage/configuration/config_documentation.md
- synapse/handlers/room.py
The existing docs make it clear that setting `default_power_level_content_override` for a preset removes all the defaults for that preset. The docs don't say what the defaults are …
> Improve default_power_level_content_override documentation

- changelog.d/17458.misc
- synapse/handlers/sliding_sync.py
This is also what we do for standard `/sync`.
> Generate room sync data concurrently

- changelog.d/17433.feature
- docs/usage/configuration/config_documentation.md
- synapse/_scripts/synapse_port_db.py
- synapse/config/repository.py
- synapse/media/media_repository.py
- synapse/media/thumbnailer.py
- synapse/rest/media/download_resource.py
- synapse/rest/media/thumbnail_resource.py
- synapse/storage/databases/main/media_repository.py
- synapse/storage/schema/__init__.py
- synapse/storage/schema/main/delta/86/01_authenticate_media.sql
- tests/rest/client/test_media.py
As part of the rollout of [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3916-authentication-for-media.md) this PR adds support for designating authenticated media and ensuring that authenticated media is not served over unauthenticated endpoints.
Should be reviewable commit-by-commit.
> Prepare for authenticated media freeze

- changelog.d/17461.misc
- synapse/handlers/e2e_room_keys.py
Linaerizing all access slows things down when devices try and fetch lots of keys on login
> Speed up room keys query by using read/write lock

- changelog.d/17469.misc
- synapse/handlers/sliding_sync.py
- tests/rest/client/test_sync.py
`$ME` can be used as a substitute for the requester's user ID.
> SS: Implement `$ME` support

- changelog.d/17454.feature
- synapse/handlers/device.py
- synapse/handlers/sliding_sync.py
- synapse/rest/client/keys.py
- synapse/rest/client/sync.py
- synapse/types/__init__.py
- synapse/types/handlers/__init__.py
- synapse/types/rest/client/__init__.py
- tests/rest/client/test_sync.py
For Sliding Sync, add E2EE extension ([MSC3884](https://github.com/matrix-org/matrix-spec-proposals/pull/3884))
Based on [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575): Sliding Sync
Previous Sliding Sync extension: https://github.com/element-hq/synapse/pull/17416
Previous `/sync/e2ee` endpoint: https://github.com/element-hq/synapse/pull/17167
`device_lists`, `device_one_time_keys_count`, `device_unused_fallback_key_types` spec: https://spec.matrix.org/v1.10/client-server-api/#e2e-extensions-to-sync
---
Instead of the complicated device list change calculation that `/sync` v2 does, we can just re-use the work from the `/keys/changes` endpoint.
---
Other things:
- `get_forward_extremities_for_room_at_stream_ordering(...)` ("Fetch the current state at the time.")
- …
> Sliding Sync: Add E2EE extension (MSC3884)

- changelog.d/17231.bugfix
- docs/usage/configuration/config_documentation.md
- synapse/config/server.py
- synapse/handlers/sync.py
- tests/module_api/test_api.py
This is to address an issue in which `m.presence` results on initial sync are not returning entries of users who are currently offline. I believe this was intended behavior as stated in https://github.com/element-hq/synapse/issues/1535, but since this was 8+ years ago, I wanted to check if that is still the case. If this is still desired behavior, then feel free to close the PR.
However, I think this change is useful for applications that use the presence system for tracking user profile information/updates (e.g. https://github.com/element-hq/synapse/pull/16992 or for profile status messages). 
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to …
> Fixed presence results not returning offline users on initial sync

- changelog.d/17428.bugfix
- synapse/notifier.py
- synapse/types/__init__.py
Introduced in: #17215
This caused us a minor bit of grief as the volume of logs produced was much higher than normal
> Reduce volume of 'Waiting for current token' logs, which were introduced in v1.109.0.

- changelog.d/17468.misc
- synapse/handlers/sliding_sync.py
- synapse/storage/databases/main/event_federation.py
- synapse/storage/databases/main/stream.py
- synapse/util/caches/stream_change_cache.py
- tests/util/test_stream_change_cache.py
We do this by bulk fetching the latest stream ordering.
> Speed up SS room sorting

- changelog.d/17452.misc
- synapse/handlers/sliding_sync.py
- synapse/rest/client/sync.py
- synapse/types/__init__.py
- synapse/types/handlers/__init__.py
- tests/rest/client/test_sync.py
This is in preparation for adding per-connection state.
> Use a new token format for sliding sync

- changelog.d/17478.misc
- synapse/handlers/sliding_sync.py
- tests/rest/client/test_sync.py
Backfill events have a negative stream ordering, and so its not useful to use to compare with other (positive) stream orderings.
Plus, the Rust SDK currently assumes `bump_stamp` is positive.
> Sliding Sync: ensure bump stamp ignores backfilled events

- changelog.d/17477.feature
- synapse/handlers/sliding_sync.py
- synapse/rest/client/sync.py
- synapse/types/handlers/__init__.py
- synapse/types/rest/client/__init__.py
- tests/rest/client/test_sync.py
For Sliding Sync, add Account Data (`account_data`) extension ([MSC3959](https://github.com/matrix-org/matrix-spec-proposals/pull/3959))
Based on [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575): Sliding Sync
Sliding Sync extensions spec for how the `lists` and `rooms` parameters should work: https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#extensions
```
SYNAPSE_TEST_LOG_LEVEL=INFO poetry run trial tests.rest.client.test_sync.SlidingSyncAccountDataExtensionTestCase
```
- Use markdown where necessary, mostly for `code …
> Sliding Sync: Add Account Data extension (MSC3959)

- changelog.d/17476.doc
- docs/usage/configuration/config_documentation.md
change the example configuration of msisdn in `allowed_local_3pids`, which is a bit misleading that regex pattern has leading '+'
> Update config_documentation - Change example of msisdn in allowed_local_3pids

- changelog.d/17481.misc
- tests/rest/client/test_sync.py
Refactor Sliding Sync tests to better utilize the `SlidingSyncBase` (pt. 1)
`SlidingSyncBase` for tests was first introduced in https://github.com/element-hq/synapse/pull/17452
Part 2: https://github.com/element-hq/synapse/pull/17482
(run the …
> Refactor Sliding Sync tests to better utilize the `SlidingSyncBase` (pt. 1)

- changelog.d/17482.misc
- tests/rest/client/test_sync.py
Refactor Sliding Sync tests to better utilize the `SlidingSyncBase.do_sync(...)` (pt. 2)
`SlidingSyncBase.do_sync()` for tests was first introduced in https://github.com/element-hq/synapse/pull/17452
Part 1: https://github.com/element-hq/synapse/pull/17481
(run the …
> Refactor Sliding Sync tests to better utilize the `SlidingSyncBase.do_sync(...)` (pt. 2)

- changelog.d/17499.bugfix
- synapse/handlers/e2e_keys.py
- tests/handlers/test_e2e_keys.py
Fixes: https://github.com/element-hq/synapse/issues/17498
Fixes: https://github.com/element-hq/element-web/issues/27867
> Fix `failures` property in `/keys/query`

- changelog.d/17501.misc
- synapse/handlers/sliding_sync.py
- synapse/rest/client/sync.py
This will make it easier to see what it is doing in jaeger.
> Add some more opentracing to sliding sync

- changelog.d/17507.misc
- synapse/types/handlers/__init__.py
Sliding Sync: Fix `limited` response description (make accurate)
> Sliding Sync: Fix `limited` response description (make accurate)

- changelog.d/17511.misc
- tests/rest/client/sliding_sync/test_rooms_timeline.py
Easier to understand timeline assertions in tests
Added `_assertTimelineEqual(...)` because I got fed up trying to understand the crazy diffs from the standard `self.assertEqual(...)`/`self.assertListEqual(...)`
Before:
```
[FAIL]
Traceback (most recent call last):
File "/home/eric/Documents/github/element/synapse/tests/rest/client/sliding_sync/test_rooms_timeline.py", line 103, in test_rooms_limited_initial_sync
self.assertListEqual(
File "/usr/lib/python3.12/unittest/case.py", line 1091, in assertListEqual
self.assertSequenceEqual(list1, list2, msg, seq_type=list)
File "/usr/lib/python3.12/unittest/case.py", line 1073, in assertSequenceEqual
self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: ['$4QcmnzhdazSnDYcYSZCS_6-MWSzM_dN3RC7TRvW0w[95 chars]isM'] != …
```
> Sliding Sync: Easier to understand timeline assertions in tests

- changelog.d/17529.misc
- synapse/api/errors.py
- synapse/handlers/sliding_sync.py
- tests/rest/client/sliding_sync/test_rooms_required_state.py
This triggers the client to start a new sliding sync connection. If we don't do this and the client asks for the full range of rooms, we end up sending down all rooms and their state from scratch (which can be very slow)
This causes things like https://github.com/element-hq/element-x-ios/issues/3115 after we restart the server
> SS: Reset connection if token is unrecognized

- changelog.d/17514.misc
- synapse/handlers/sliding_sync.py
- synapse/rest/client/sync.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/databases/main/state_deltas.py
- synapse/storage/databases/main/stream.py
Add more tracing. Spawning from looking at a couple traces and wanting a little more info.
Follow-up to github.com/element-hq/synapse/pull/17501
---
The changes in this PR allow you to find slow Sliding Sync traces ignoring the `wait_for_events` time. In Jaeger, you can now filter for the `current_sync_for_user` operation with `RESULT.result=true` indicating that it actually returned non-empty results.
If you want to find traces for your own user, you can use `RESULT.result=true ARG.sync_config.user="@madlittlemods:matrix.org"`
- …
> Sliding Sync: Add more tracing

- changelog.d/17531.misc
- synapse/api/errors.py
c.f. https://github.com/element-hq/synapse/pull/17529#discussion_r1705780925
> Fixup sliding sync comment

- changelog.d/17535.bugfix
- synapse/handlers/sliding_sync.py
- tests/rest/client/sliding_sync/test_connection_tracking.py
Implement tracking of rooms that have had updates that have not been sent down to clients.
Simplified Sliding Sync (SSS)
> SSS: Implement PREVIOUSLY room tracking

- .github/workflows/tests.yml
- changelog.d/17536.misc
- scripts-dev/federation_client.py
This PR replaces the deprecated `get_connection` method in `MatrixConnectionAdapter` with a similar implementation in `get_connection_with_tls_context`. It also fixes a couple mypy errors that were firing on the arguments of `get_connection`.
See context for the deprecated method here: https://github.com/psf/requests/pull/6710
Fixes the errors raised in https://github.com/element-hq/synapse/pull/17524
> Replace deprecated `HTTPAdapter.get_connection` method with  `get_connection_with_tls_context`

- changelog.d/17537.misc
- synapse/handlers/device.py
- synapse/handlers/sync.py
- synapse/storage/databases/main/state_deltas.py
We do this by reusing the code from sync v2.
Reviewable commit-by-commit.  The function `get_user_ids_changed` has been rewritten entirely, so I would recommend not looking at the diff.
> Fix performance of device lists in `/key/changes` and sliding sync

- changelog.d/17542.misc
- poetry.lock
This PR bumps `setuptools` after we had to [revert a previous bump](https://github.com/element-hq/synapse/pull/17455) due to [a regression](https://github.com/pypa/setuptools/issues/4399).
> Bump setuptools from 67.6.0 to 72.1.0

- changelog.d/17561.misc
- synapse/media/_base.py
> Fixup media logcontexts

- changelog.d/17563.misc
- synapse/http/client.py
This is really spurious and causes a lot of spam. I don't think there is a use for it even at DEBUG level.
> Remove logging in multipart

- changelog.d/17559.doc
- synapse/handlers/profile.py
- synapse/storage/databases/main/profile.py
> Add missing docstrings related to profile methods.

- changelog.d/17564.misc
- synapse/media/_base.py
- synapse/media/media_storage.py
- synapse/media/storage_provider.py
- synapse/media/thumbnailer.py
- synapse/server.py
- tests/server.py
Otherwise we end up using the default one with just 10 threads.
> Use a larger, dedicated threadpool for media sending

- changelog.d/17545.bugfix
- synapse/http/client.py
- tests/http/test_client.py
> Handle lower-case http headers in `_Mulitpart_Parser_Protocol`

- changelog.d/17567.misc
- synapse/media/_base.py
- synapse/util/async_helpers.py
Follow on from #17558
Basically, we want to reduce the number of threads we want to use at a time, i.e. reduce the number of threads that are paused/blocked. We do this by returning from the thread when the consumer pauses the producer, rather than pausing in the thread.
> Reduce concurrent thread usage in media

- changelog.d/17568.bugfix
- synapse/crypto/keyring.py
`old_verify_keys` isn't marked as required in https://spec.matrix.org/v1.11/server-server-api/#get_matrixkeyv2server and there's no functional difference between an empty object and omitting the object, so I don't think there's any reason synapse should explode when the field is omitted.
> Fix fetching signing keys when `old_verify_keys` is omitted

- changelog.d/17566.misc
- synapse/server.py
Missed in #17564. Otherwise it won't be visible in our graphs.
> Register the media threadpool with our metrics

- changelog.d/17571.misc
- synapse/rest/client/versions.py
So that clients can check for support. Note that if the feature is only enabled for some users, the `/versions` request must be authenticated to pick up that SSS is enabled for the user
> Add a flag to /versions about SSS support

- changelog.d/17548.misc
- synapse/handlers/device.py
- synapse/storage/databases/main/state_deltas.py
Follow on from #17537.
This is just adding a batched lookup function (you might want to hide whitespace in the diff).
> Speed up `/keys/changes`

- changelog.d/17562.misc
- scripts-dev/release.py
This stops people from getting half way through a step and it failing due to the github token having expired (this happens to me every damn time).
> Test github token before running release script

- changelog.d/17570.bugfix
- synapse/media/media_storage.py
Results in:
```
AssertionError: null
File "synapse/http/server.py", line 332, in _async_render_wrapper
callback_return = await self._async_render(request)
File "synapse/http/server.py", line 544, in _async_render
callback_return = await raw_callback_return
File "synapse/federation/transport/server/_base.py", line 369, in new_func
response = await func(
File "synapse/federation/transport/server/federation.py", line 826, in on_GET
await self.media_repo.get_local_media(
File "synapse/media/media_repository.py", line 473, in get_local_media
await respond_with_multipart_responder(
File "synapse/media/_base.py", line 353, in respond_with_multipart_responder
assert content_length is not None
```
> Fix zero length media handling

- changelog.d/17574.misc
- synapse/handlers/sliding_sync.py
This is some prep work ahead of correctly tracking receipts, where we will also want to track the room status in terms of last receipt we had sent down.
Essentially, we add two classes `PerConnectionState` and a mutable version, and then operate on those.
> Sliding sync: Add classes for per-connection state

- changelog.d/17589.misc
- synapse/handlers/sliding_sync.py
This is to make initial sliding sync a bit faster
> Sliding Sync: Batch up fetching receipts

- changelog.d/17593.misc
- synapse/handlers/sliding_sync.py
This should let us see how quickly we actually process things in practice.
> Add metrics for sliding sync processing time

- changelog.d/17604.misc
- synapse/logging/opentracing.py
The decorator assumed we were always wrapping function methods
> Fix @tag_args for non-methods

- changelog.d/17606.misc
- synapse/storage/databases/main/cache.py
- synapse/storage/databases/main/stream.py
The idea is to engineer it so that the vast majority of the rooms can stay in the cache, so we can just ignore them.
> Speed up fetching latest stream positions via cache

- changelog.d/17608.feature
- debian/hash_password.1
- debian/hash_password.1.html
- debian/hash_password.ronn
- synapse/_scripts/hash_password.py
`hash_password` now actually accepts password from stdin. The `getpass` reads from TTY, and does NOT accept stdin in any way.
The manpage has been updated to reflect that.
> hash_password accepts stdin now

- changelog.d/17532.bugfix
- synapse/media/_base.py
- synapse/media/media_repository.py
- synapse/media/thumbnailer.py
`/_matrix/federation/v1/media/thumbnail/` responses were failing due to the endpoint returning the wrong content-length. This was due to the content-length being calculated off of the length of the original media file, rather than the thumbnail file. 
Fixes #17518.
Complement test at https://github.com/matrix-org/complement/pull/732
> Fix content length on federation `/thumbnail` responses

- changelog.d/17194.bugfix
- synapse/handlers/room_summary.py
- tests/handlers/test_room_summary.py
> Fix hierarchy returning 403 when room is accessible through federation

- changelog.d/17617.misc
- synapse/handlers/sliding_sync/extensions.py
- synapse/storage/databases/main/receipts.py
- tests/rest/client/sliding_sync/test_extension_receipts.py
When returning receipts in sliding sync for initial rooms we should always include our own receipts in the room (even if they don't match any timeline events).
Reviewable commit-by-commit.
> Sliding sync: Always send your own receipts down

- changelog.d/17590.doc
- docs/usage/configuration/config_documentation.md
Only fix doc.
This was a "drive by change" in https://github.com/element-hq/synapse/commit/6d47b7e32589e816eb766446cc1ff19ea73fc7c1#diff-21eb1b3b6455b7011ccbffc74b0279d87d5c69752d62d0 …
> fix listener docs - admin api only on main process

- changelog.d/17631.misc
- synapse/storage/databases/main/events_bg_updates.py
- tests/storage/test_sliding_sync_tables.py
This reverts commit ab414f2ab8a294fbffb417003eeea0f14bbd6588.
Introduced in https://github.com/element-hq/synapse/pull/17599
> Fix background update for sliding sync

- changelog.d/17632.misc
- synapse/storage/databases/main/events_bg_updates.py
This reverts commit https://github.com/element-hq/synapse/commit/ab414f2ab8a294fbffb417003eeea0f14bbd6588.
Introduced in https://github.com/element-hq/synapse/pull/17512
> Fix background update for sliding sync (find previous membership)

- changelog.d/17635.misc
- synapse/api/constants.py
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/events_bg_updates.py
- tests/storage/test_sliding_sync_tables.py
Fix outlier re-persisting causing problems with sliding sync tables
Follow-up to https://github.com/element-hq/synapse/pull/17512
When running on `matrix.org`, we discovered that a remote invite is first persisted as an `outlier` and then re-persisted again where it is de-outliered. The first the time, the `outlier` is persisted with one `stream_ordering` but when persisted again and de-outliered, it is assigned a different `stream_ordering` that won't end up being used. Since we call `_calculate_sliding_sync_table_changes()` before `_update_outliers_txn()` which fixes this discrepancy (always use the `stream_ordering` from the first time it was persisted), we're working with an unreliable `stream_ordering` value that will possibly be unused and not make it into the `events` table.
``` …
```
> Sliding Sync: Fix outlier re-persisting causing problems with sliding sync tables

- changelog.d/17634.misc
- synapse/storage/databases/main/events_bg_updates.py
Follow-up to https://github.com/element-hq/synapse/pull/17631 and https://github.com/element-hq/synapse/pull/17632 to fix-up https://github.com/element-hq/synapse/pull/17599
> Sliding sync: Fix bg update again (v3)

- changelog.d/17509.feature
- synapse/rest/client/auth.py
- synapse/rest/client/keys.py
- tests/handlers/test_oauth_delegation.py
- tests/rest/client/test_keys.py
Rather than 501 M_UNRECOGNISED
Client side impl https://github.com/matrix-org/matrix-react-sdk/pull/12892/
> Use custom stage UIA error for MAS cross-signing reset

- changelog.d/17636.misc
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/databases/main/events_worker.py
Follows on from #17512, other fixes include: #17633, #17634, #17635
> Sliding sync: various fixes to background update

- changelog.d/17629.misc
- synapse/handlers/sliding_sync/room_lists.py
This is to make it easier to reuse the logic when adding support for the new tables
> Sliding Sync: Split up `get_room_membership_for_user_at_to_token`

- changelog.d/17649.misc
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/databases/main/roommember.py
> Fix sliding sync on workers

- changelog.d/17655.misc
- synapse/handlers/sliding_sync/__init__.py
Prevent duplicate tags being added to traces.
Noticed because we see these warnings in Jaeger:
> Sliding Sync: Prevent duplicate tags being added to traces

- changelog.d/17641.misc
- synapse/storage/databases/main/events_bg_updates.py
Follow-up to #17634, https://github.com/element-hq/synapse/pull/17631 and https://github.com/element-hq/synapse/pull/17632 to fix-up https://github.com/element-hq/synapse/pull/17512
> Fix background update to handle invalid events

- changelog.d/17650.removal
- synapse/config/experimental.py
- synapse/rest/client/knock.py
- synapse/rest/client/room.py
[MSC4156](https://github.com/matrix-org/matrix-spec-proposals/pull/4156) has been merged so unstable prefixes are no longer required.
> Stabilise MSC4156: `server_name` -> `via`

- changelog.d/17670.misc
- synapse/handlers/sliding_sync/__init__.py
- synapse/handlers/sliding_sync/room_lists.py
- synapse/storage/roommember.py
- tests/handlers/test_sliding_sync.py
We ended up spending ~10% CPU creating a new dictionary and `_RoomMembershipForUser`, so let's avoid creating new dicts and copying by returning `newly_joined`, `newly_left` and `is_dm` as sets directly.
> Speed up sliding sync by avoiding copies

- changelog.d/17666.misc
- synapse/handlers/sliding_sync/room_lists.py
- synapse/storage/databases/main/room.py
Instead of having a large cache of `room_id -> bool` about whether a room is partially stated, replace with a "fetch rooms the user is which are partially-stated". This is a lot faster as the set of partially stated rooms at any point across the whole server is small, and so such a query is fast.
The main issue with the bulk cache lookup is the CPU time looking all the rooms up in the cache.
> Speed up fetching partial-state rooms on sliding sync

- changelog.d/17674.bugfix
- synapse/handlers/sliding_sync/__init__.py
- tests/rest/client/sliding_sync/test_rooms_meta.py
We should only look for bump stamps in joined rooms, otherwise we should just use the membership stream ordering.
> Fix bump stamp for non-joined rooms

- changelog.d/17665.misc
- synapse/handlers/sliding_sync/__init__.py
- synapse/rest/client/sync.py
- synapse/types/handlers/sliding_sync.py
- tests/rest/client/sliding_sync/test_rooms_meta.py
Speed up incremental sync by avoiding extra work. We first look at the state delta changes and only fetch and calculate further derived things if they have changed.
This isn't a very good trace comparison because these are just from some synthetic local tests that have too little data and run so fast that there is a lot of variation in the span durations. The main thing to notice is that the `get_current_state_ids_at(...)` chunk isn't happening the after trace.
Before | After
--- | ---
Trace before: [`aded9b5d1d517d83.json`](https://gist.github.com/MadLittleMods/aa2ffc3d82d78bcb4040a387731cd2af)
Trace after: [`48dee2667089b630.json`](https://gist.github.com/MadLittleMods/7e7d8b970e6606fcba9b28daa7c93e24)
The real-world trace before …
> Sliding Sync: Speed up incremental sync by avoiding extra work

- changelog.d/17654.misc
- synapse/storage/databases/main/events_bg_updates.py
Add comment to explain extra case where you can be invited -> banned -> unbanned and we want to be able to find the invite event.
Follow-up to https://github.com/element-hq/synapse/pull/17636#discussion_r1738993330
(run the [linters](https://element-hq.github.io/synapse/latest/development/contributi …
> Sliding Sync: Add comment to explain extra case where you can be invited -> banned -> unbanned

- changelog.d/17688.misc
- synapse/handlers/admin.py
- synapse/handlers/pagination.py
- synapse/handlers/room.py
- synapse/handlers/sliding_sync/__init__.py
- synapse/handlers/sync.py
- synapse/storage/databases/main/stream.py
- tests/rest/client/sliding_sync/test_rooms_timeline.py
- tests/storage/test_stream.py
When using timeline limit of 1 we end up fetching 2 events from the DB purely to tell if the response was "limited" or not. Lets not do that.
> Sliding Sync: Retrieve fewer events from DB in sync

- changelog.d/17684.misc
- synapse/handlers/sliding_sync/__init__.py
This allows us to skip checking the database a lot of the time.
> Sliding Sync: Look for `bump _stamp` in the room timeline

- changelog.d/17673.misc
- synapse/storage/databases/main/events_bg_updates.py
Follow-up to #17652, https://github.com/element-hq/synapse/pull/17641, https://github.com/element-hq/synapse/pull/17634, https://github.com/element-hq/synapse/pull/17631 and https://github.com/element-hq/synapse/pull/17632 to fix-up https://github.com/element-hq/synapse/pull/17512
> Sliding sync: various fixups to the sliding sync joined room background job

- changelog.d/17690.feature
- docs/usage/configuration/config_documentation.md
- synapse/config/voip.py
Add the config option `turn_shared_secret_path` and accompanying docs. The config allows Synapse to read the TURN shared secret from a file. The code was shamelessly adapted from the implementation of `registration_shared_secret_path`.
Reading secrets from files has the security advantage of separating the secrets from the config. It also simplifies secrets management in Kubernetes.
- Feel free to credit yourself, by adding a sentence …
> Add config option turn_shared_secret_path

- changelog.d/17675.feature
- synapse/rest/client/media.py
I didn't see tests for other guest access endpoints in my 15 seconds of searching, but if there's guidance on how to set that up, happy to add the respective tests.
> Enable guest access on new media endpoints, per MSC4189

- changelog.d/17683.misc
- synapse/handlers/sliding_sync/__init__.py
- synapse/storage/_base.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/databases/main/state.py
- synapse/storage/schema/main/delta/87/03_current_state_index.sql
- tests/rest/client/sliding_sync/test_rooms_meta.py
For rooms with a name we can skip fetching a full room summary, as we don't need to calculate heroes, and instead just fetch the room counts directly.
This also changes things to not return counts and heroes for non-joined rooms. For left/banned rooms we were returning zero values anyway, and for invite/knock rooms we don't really want to leak such information (even if some of is included in the stripped state).
> Sliding sync: don't fetch room summary for named rooms.

- changelog.d/17693.misc
- synapse/handlers/sliding_sync/room_lists.py
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/databases/main/events_worker.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/databases/main/stream.py
- synapse/types/storage/__init__.py
- tests/storage/test_sliding_sync_tables.py
Use Sliding Sync tables for sorting (`bulk_get_last_event_pos_in_room_before_stream_ordering(...)` -> `_bulk_get_max_event_pos(...)`)
> Sliding Sync: Use Sliding Sync tables for sorting

- changelog.d/17667.misc
- scripts-dev/check_pydantic_models.py
- synapse/_pydantic_compat.py
- synapse/config/_util.py
- synapse/config/workers.py
- synapse/events/validator.py
- synapse/http/servlet.py
- synapse/rest/admin/users.py
- synapse/rest/client/account.py
- synapse/rest/client/devices.py
- synapse/rest/client/directory.py
- synapse/rest/client/reporting.py
- synapse/rest/key/v2/remote_key_resource.py
- synapse/storage/background_updates.py
- synapse/types/handlers/sliding_sync.py
- synapse/types/rest/__init__.py
- synapse/types/rest/client/__init__.py
- tests/rest/client/test_models.py
This PR changes `from pydantic import BaseModel` to `from synapse._pydantic_compat import BaseModel` (as well as `constr`, `conbytes`, `conint`, `confloat`).
It allows `check_pydantic_models.py` to mock those pydantic objects only in the synapse module, and not interfere with pydantic objects in external dependencies.
This should solve the CI problems for #17144, which breaks because `check_pydantic_models.py` patches pydantic models from [scim2-models](https://scim2-models.readthedocs.io/).
/cc @DMRobertson @gotmax23
fixes #17659 
- Use markdown where necessary, mostly for `code …
> import pydantic objects from the `_pydantic_compat` module

- changelog.d/17696.misc
- synapse/handlers/sliding_sync/__init__.py
- synapse/handlers/sliding_sync/extensions.py
For initial requests a typical page size is 20 rooms, so we may as well do the batching as 20. 
This should speed up bigger syncs a little bit.
> Sliding Sync: Increase concurrency of sliding sync a bit

- changelog.d/17662.feature
- synapse/handlers/sliding_sync/room_lists.py
- tests/handlers/test_sliding_sync.py
- tests/rest/client/sliding_sync/test_lists_filters.py
This appears to be enough to make Element Web work (or at least move it on to the next hurdle), although I'm not super confident in it, especially the tests since the `is_dm` tests were testing a different filter method. The tests are also just at the lowest unit level rather than anything higher. I'm not sure what the difference is between the two filter methods - I guess we would need to add both?
Simplified Sliding Sync (SSS)
- Feel free …
> Sliding Sync: Support filtering by 'tags' / 'not_tags' in SSS

- changelog.d/17707.feature
- synapse/handlers/sliding_sync/extensions.py
- synapse/storage/databases/main/account_data.py
- synapse/types/handlers/sliding_sync.py
- tests/rest/client/sliding_sync/test_extension_account_data.py
Return room tags in account data extension
The account data extension was also updated to avoid copies when we pull the data out of the cache.
Fix https://github.com/element-hq/synapse/issues/17694
<details>
<summary>Sync v2 incremental sync response with some rooms tags in the account data (favouriting a room)</summary>
```json
{
"next_batch": "s5241945698_757284974_2782863_3110944073_3359903529_260642965_1380548560_11007322260_0_338462",
"device_one_time_keys_count": {
"signed_curve25519": 50
},
"org.matrix.msc2732.device_unused_fallback_key_types": [
"signed_curve25519"
],
"device_unused_fallback_key_types": [
"signed_curve25519"
],
"rooms": {
"join": {
"!xxx:matrix.org": {
"timeline": {
"events": [],
"prev_batch": "s5241945695_757284974_2782854_3110944063_3359903514_260642965_138054855 …
```
> Sliding Sync: Return room tags in account data extension

- changelog.d/17723.misc
- synapse/handlers/sliding_sync/__init__.py
Short-circuit `have_finished_sliding_sync_background_jobs`. We only need to check it if returned bump stamp is `None`, which is rare.
Pulling this change out from one of @erikjohnston's branches (https://github.com/element-hq/synapse/compare/develop...erikj/ss_perf)
(run the …
> Sliding Sync: Short-circuit `have_finished_sliding_sync_background_jobs`

- changelog.d/17727.bugfix
- synapse/storage/databases/main/stream.py
Fixes https://github.com/element-hq/element-x-ios/issues/3300
Some rooms are missing from `sliding_sync_joined_rooms`. When this happens, the first call will succeed, but any subsequent calls for this room ID will cause the cache to return `None` for the room ID, rather than not having the key at all. This then causes the `<=` check to throw.
Root cause: https://github.com/element-hq/synapse/issues/17726
- Feel free to credit yourself, by …
> Sliding Sync: bugfix: ensure we can sync with SSS even with missing rooms

- changelog.d/17724.misc
- synapse/storage/background_updates.py
Shortcut for checking if certain background updates have completed
Pulling this change out from one of @erikjohnston's branches (https://github.com/element-hq/synapse/compare/develop...erikj/ss_perf)
(run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#r …
> Sliding Sync: Shortcut for checking if certain background updates have completed

- changelog.d/17728.misc
- synapse/storage/databases/main/stream.py
Fix `_bulk_get_max_event_pos(...)` being inefficient. It kept adding all of the `batch_results` to the `results` over and over every time we checked a single room in the batch.
I think we still ended up with the right answer before because we accumulate `recheck_rooms` and actually recheck them to overwrite the bad data we wrote to the `results` before.
Introduced in https://github.com/element-hq/synapse/pull/17606/files#diff-cbd54e4b5a2a1646299d659a2d5884d6cb14e608efd2e1658e72b465bb66e31bR1481
- End with either a period (.) or …
> Sliding Sync: Fix `_bulk_get_max_event_pos(...)` being inefficient

- changelog.d/17731.misc
- synapse/handlers/sliding_sync/room_lists.py
- tests/rest/client/sliding_sync/test_lists_filters.py
- tests/rest/client/sliding_sync/test_rooms_meta.py
- tests/rest/client/sliding_sync/test_sliding_sync.py
No need to sort if the range is large enough to cover all of the rooms in the list. Previously, we would only do this optimization if the range was exactly large enough.
Follow-up to https://github.com/element-hq/synapse/pull/17672
(run the …
> Sliding Sync: No need to sort if the range is large enough to cover all of the rooms

- changelog.d/17730.misc
- synapse/handlers/account_data.py
- synapse/storage/databases/main/cache.py
- synapse/storage/databases/main/tags.py
- tests/server_notices/test_resource_limits_server_notices.py
Add cache to `get_tags_for_room(...)`
This helps Sliding Sync because `get_tags_for_room(...)` is going to be used in https://github.com/element-hq/synapse/pull/17695
Essentially, we're just trying to match `get_account_data_for_room(...)` which already has a tree cache.
(run the …
> Sliding Sync: Add cache to `get_tags_for_room(...)`

- changelog.d/17733.bugfix
- synapse/handlers/sliding_sync/room_lists.py
- synapse/storage/databases/main/roommember.py
- tests/rest/client/sliding_sync/test_rooms_meta.py
Follow on from #17727
Example stack trace:
```
Traceback (most recent call last):
File "/synapse/synapse/http/server.py", line 332, in _async_render_wrapper
callback_return = await self._async_render(request)
File "/synapse/synapse/http/server.py", line 544, in _async_render
callback_return = await raw_callback_return
File "/synapse/synapse/rest/client/sync.py", line 940, in on_POST
sliding_sync_results = await self.sliding_sync_handler.wait_for_sync_for_user(
File "/synapse/synapse/handlers/sliding_sync/__init__.py", line 151, in wait_for_sync_for_user
result = await self.current_sync_for_user(
File "/synapse/synapse/logging/opentracing.py", line 922, in _wrapper
return await func(*args, **kwargs)
File "/synapse/synapse/handlers/sliding_sync/__init__.py", line 228, in …
```
> Fix sliding sync for rooms with unknown room version

- changelog.d/17725.misc
- synapse/handlers/sliding_sync/__init__.py
- synapse/handlers/sliding_sync/room_lists.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/databases/main/state.py
- synapse/storage/databases/main/stream.py
- tests/rest/client/sliding_sync/test_sliding_sync.py
- tests/storage/test_stream.py
Performance optimization: We can avoid fetching rooms that the user has left themselves (which could be a significant amount), then only add back rooms that the user has `newly_left` (left in the token range of an incremental sync). It's a lot faster to fetch less rooms than fetch them all and throw them away in most cases. Since the user only leaves a room (or is state reset out) once in a blue moon, we can avoid a lot of work.
Based on @erikjohnston's branch, https://github.com/element-hq/synapse/compare/develop...erikj/ss_perf …
> Sliding Sync: Avoid fetching left rooms and add back `newly_left` rooms

- changelog.d/17734.misc
- synapse/handlers/sliding_sync/room_lists.py
We do this by using the event stream cache.
> Speed up sorting of sliding sync rooms in initial request

- changelog.d/17748.bugfix
- synapse/handlers/sliding_sync/__init__.py
> Never return negative bump stamp

- changelog.d/17741.misc
- contrib/graph/graph.py
- synapse/event_auth.py
- synapse/http/matrixfederationclient.py
Removes all uses of the `cgi` module from Synapse. It was deprecated in Python version 3.11 and removed in version 3.13 ([“dead battery”](https://docs.python.org/3.13/whatsnew/3.13.html#pep-594-remove-dead-batteries-from-the-standard-library)). 
(run the …
> Remove the deprecated cgi module

- changelog.d/17749.doc
- docs/setup/installation.md
This was a note added in the PR to move to AGPL, which we failed to remove before landing. 
(The context for this was that we needed to decide if we were going to change which debian repository we published too, but decided not to in the end)
> Remove spurious TODO in debian install step

- changelog.d/17751.misc
- synapse/handlers/sliding_sync/extensions.py
This works as instead of passing *all* rooms to `record_sent_rooms` we only need to pass rooms that were previously not in the LIVE state.
This came from a py-spy where we were spending ~10% CPU calling these functions. Note that `record_sent_rooms` is a no-op for rooms that are already in the `LIVE` state, so we only need to call them for `PREVIOUSLY` or `INITIAL` rooms.
> Minor perf speed up for large accounts on SSS

- changelog.d/17765.misc
- synapse/notifier.py
- tests/rest/client/test_sync.py
The notifier is quite inefficient when it has to wake up many user streams all at once
From a silly benchmark this takes the time to notify 1M user streams from ~30s to ~5s
> Optimise notifier

- changelog.d/17768.misc
- synapse/handlers/sliding_sync/__init__.py
- synapse/handlers/sliding_sync/room_lists.py
Principally useful for EX e2ee sliding sync connections.
> Add fast path for sliding sync streams that only ask for extensions

- changelog.d/17771.misc
- synapse/api/auth/msc3861_delegated.py
- synapse/handlers/device.py
Mainly toning down logging and only calling `get_membership_from_event_ids` if something has changed.
> Reduce overhead of sliding sync E2EE loops

- changelog.d/17767.misc
- synapse/util/caches/stream_change_cache.py
- tests/util/test_stream_change_cache.py
There is a bug with the `StreamChangeCache` where it would incorrectly return that all entities had changed if asked for entities changed *since* the earliest stream position.
Note that for streams we use the inequalities: `$min_stream_id < stream_id <= $max_stream_id`, i.e. when we ask the stream change cache for all things that have changed since `$stream_id` we don't care for events that happened *at* `$stream_id`.
Specifically: `_earliest_known_stream_pos` is the position at which we know that we'll have entries for all changes since that point, we can use the cache for any stream IDs that equal `_earliest_known_stream_pos`.
`_earliest_known_stream_pos` is set in three places:
- On startup we set it either to:
- the current maximum stream ID, with not prefilled values; or
- the …
> Fix perf when streams don't change often

- changelog.d/17776.doc
- docs/usage/configuration/config_documentation.md
Adding information on how the load is distributed for `federation_sender_instances`.
Thx to @devonh for the information.
causal source: https://github.com/element-hq/synapse/blob/c2e5e9e67c24264f5a12bf3ceaa9c4e195547d26/synapse/config/_base.py#L946-L989
(run the …
> explain load balancing for `federation_sender_instances`

- changelog.d/17779.bugfix
- synapse/replication/http/push.py
Looks like a copy-paste error. One way to prevent this in the future is having a test that checks that no two replication endpoints have the same `NAME`. Or generating `NAME` based on the class name.
---
The PR that originally [introduced this replication endpoint](https://github.com/matrix-org/synapse/pull/9465) mentioned that there were currently no users of it. Indeed, I could only find one (very rare) codepath that called `PusherPool.remove_pusher` from a worker, which was:
https://github.com/element-hq/synapse/blob/5acd8d258c6b93fe8d7e9c082d10cf52c5efc9b2/synapse/module_api/__init__.py#L912-L915
https://github.com/element-hq/synapse/blob/d4e3ad04cd722e3c98c85685d47a6d86029ffe0c/synapse/handlers/auth.py#L1514-L1516
So only if a Synapse module called `invalidate_access_token` while …
> Fix NAME attribute of `ReplicationRemovePusherRestServlet`

- changelog.d/17709.doc
- docs/usage/administration/admin_faq.md
Added a note in the documentation suggesting that users may set `PYTHONMALLOC=malloc` when using `jemalloc`. This allows jemalloc to track memory usage more accurately by bypassing Python's internal small-object allocator (`pymalloc`), helping to ensure that `cache_autotuning` functions as expected.
This doc change aims to provide more clarity for users configuring jemalloc with Synapse.
Based on: https://github.com/element-hq/synapse/blob/4ac783549c5bac7a490a715d359f330bb0b1a161/synapse/metrics/jemalloc.py#L198-L201
> docs: add note about PYTHONMALLOC for accurate jemalloc memory tracking

- changelog.d/17717.feature
- docs/usage/configuration/config_documentation.md
- synapse/config/redis.py
- tests/config/test_load.py
Adds the option to load the Redis password from a file, instead of giving it in the config directly. The code is similar to how it’s done for `registration_shared_secret_path`. I changed the example in the documentation to represent the best practice regarding the handling of secrets.
Reading secrets from files has the security advantage of separating the secrets from the config. It also simplifies secrets management in Kubernetes.
The second commit adds test cases for secret files existing and missing.
- End with either a period …
> Add config option redis.password_path

- changelog.d/17789.misc
- synapse/handlers/sliding_sync/room_lists.py
- synapse/storage/databases/main/roommember.py
Two changes: a) use a batch lookup function instead of a loop, b) check existing data to see if we already have what we need and only fetch what we don't.
> Speed up sliding sync when there are many active subscriptions

- changelog.d/17787.misc
- synapse/handlers/sliding_sync/__init__.py
- synapse/storage/databases/main/stream.py
Use the new tables to work out which rooms have changed.
> Sliding sync minor performance speed up using new table

- changelog.d/17788.misc
- synapse/handlers/sliding_sync/__init__.py
- synapse/rest/client/sync.py
- synapse/types/handlers/sliding_sync.py
- tests/rest/client/sliding_sync/test_rooms_meta.py
This saves some DB lookups in rooms
> Sliding sync: omit bump stamp when it is unchanged

- changelog.d/17792.bugfix
- synapse/handlers/admin.py
- synapse/rest/admin/users.py
- synapse/storage/databases/main/roommember.py
- tests/rest/admin/test_user.py
- better validation on user input
- fix an early task completion
- when checking membership in rooms, check for rooms user has been banned from as well
> Improvements to admin redact api

- changelog.d/17736.bugfix
- synapse/media/thumbnailer.py
The PNG format does not support non-RGB color spaces, which makes pillow raise an exception when trying to save e.g. a CMYK image in PNG format.
Converting to RGB is recommended on the [upstream issue](https://github.com/python-pillow/Pillow/issues/1380), and as CMYK is a print format transparency does not need to be considered.
Closes: #10741
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or …
> Fix saving of non-RGB thumbnails as PNG

- changelog.d/17708.feature
- docs/usage/configuration/config_documentation.md
- synapse/config/jwt.py
- synapse/handlers/jwt.py
- synapse/rest/client/login.py
- tests/rest/client/test_login.py
Added the display_name_claim option to the JWT configuration. This option allows specifying the claim key that contains the user's display name in the JWT payload.
* [] Pull request is based on the develop branch
* [] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
- Feel free to credit yourself, by adding a sentence "Contributed by …
> Added display_name_claim in jwt_config which sets the user's display name upon registration

- changelog.d/17805.bugfix
- synapse/handlers/sliding_sync/__init__.py
- tests/handlers/test_sliding_sync.py
Parameterize and add more tests for tracking changes to required state (`_required_state_changes(...)`)
These are direct modifications to https://github.com/element-hq/synapse/pull/17785 and should be merged into that PR.
(run the [linters](https://element-hq.github.io/synapse/latest/development/con …
> Sliding Sync: Parameterize and add more tests for tracking changes to required state

- changelog.d/17803.misc
- scripts-dev/release.py
The current logic didn't work.
Looks like I didn't properly test it when we added the logic in https://github.com/element-hq/synapse/pull/17562
> Fix release script to check GH token

- changelog.d/17627.doc
- docs/modules/spam_checker_callbacks.md
As folks were asking when these methods actually fire.
Please do double-check this is correct :slightly_smiling_face:
> Clarify when 3PID invite module callbacks are called

- changelog.d/17824.misc
- scripts-dev/build_debian_packages.py
c.f. https://wiki.ubuntu.com/Releases for the currently supported Ubuntu releases.
Note: this removes support for 23.04 and 23.10, which are EOL.
Fixes #17811
> Build debian packages for new Ubuntu versions

- changelog.d/17785.bugfix
- changelog.d/17805.bugfix
- synapse/handlers/sliding_sync/__init__.py
- synapse/storage/databases/main/sliding_sync.py
- synapse/types/state.py
- tests/handlers/test_sliding_sync.py
- tests/rest/client/sliding_sync/test_rooms_required_state.py
Fixes https://github.com/element-hq/synapse/issues/17698
This handles `required_state` changes by checking if new state has been added to the config, and if so fetching and returning that from the current state.
This also takes care to ensure that given a state entry S that is added, removed and then re-added that we do *not* send S down a second time if there have been no changes to S in the current state. This is fine for Rust SDK (as it just remembers all state), but we might decide not to do this behaviour in the MSC. If we decide to always send down S then its easy enough to rip out all the code.
> Correctly changes to required state config in sliding sync

- changelog.d/17718.misc
- synapse/handlers/sliding_sync/__init__.py
- synapse/storage/databases/main/events_worker.py
- tests/storage/databases/main/test_events_worker.py
- tests/unittest.py
Spawning from @kegsay [pointing out](https://matrix.to/#/!cnVVNLKqgUzNTOFQkz:matrix.org/$ExOO7J8uPUQSyH-9Uxc_QCa8jlXX9uK4VRtkSC0EI3o?via=element.io&via=matrix.org&via=jki.re) that the Sliding Sync endpoint doesn't handle a large room with a lot of state well on initial sync (requesting all state via `required_state: [ ["*","*"] ]`) (it just takes forever).
After investigating further, the slow part is just `get_events_as_list(...)` fetching all of the current state ID's out for the room (which can be 100k+ events for rooms with a lot of membership). This is just a slow thing in Synapse in general and the same thing happens in Sync v2 or the `/state` endpoint.
---
The only idea I had to improve things was to use `batch_iter` to only try fetching a fixed amount at a time instead of working …
> Sliding Sync: Slight optimization when fetching state for the room (`get_events_as_list(...)`)

- changelog.d/17826.misc
- rust/src/push/base_rules.rs
Clients will still only see this rule if the corresponding experimental feature, `msc4028_push_encrypted_events`, is also enabled.
This aligns the implementation with MSC4028, specifically [this section](https://github.com/matrix-org/matrix-spec-proposals/blob/giomfo/push_encrypted_events/proposals/4028-push-all-encrypted-events-except-for-muted-rooms.md#unstable-prefix). See https://github.com/element-hq/synapse/issues/16846 for context.
> Enable the `.org.matrix.msc4028.encrypted_event` push rule by default

- changelog.d/17835.bugfix
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/schema/__init__.py
- synapse/storage/schema/main/delta/88/02_fix_sliding_sync_membership_snapshots_forgotten_column.sql
- synapse/storage/schema/main/delta/89/01_fix_sliding_sync_membership_snapshots_forgotten_column.sql
- synapse/types/storage/__init__.py
- tests/rest/client/sliding_sync/test_sliding_sync.py
- tests/rest/client/test_rooms.py
- tests/storage/test_sliding_sync_tables.py
Reset `sliding_sync_membership_snapshots` -> `forgotten` status when membership changes (like rejoining a room).
Fix https://github.com/element-hq/synapse/issues/17781
Previously, if someone used `/forget` on one of their rooms, it would update `sliding_sync_membership_snapshots` as expected but when someone rejoined the room (or had any membership change), the upsert didn't overwrite and reset the `forgotten` status so it remained `forgotten` and invisible down the Sliding Sync endpoint.
(downside of having two sources of truth) …
> Sliding Sync: Reset `forgotten` status when membership changes (like rejoining a room)

- changelog.d/17830.misc
- synapse/federation/transport/server/_base.py
To help debug problems such as https://github.com/element-hq/synapse/issues/17822
> Include the destination in the error of 'Destination mismatch'

- changelog.d/17861.bugfix
- synapse/util/rust.py
This failed when install with poetry, so let's properly try and detect what's going on.
> Fix check for outdated Rust library

- changelog.d/17884.misc
- synapse/handlers/sliding_sync/extensions.py
- synapse/logging/context.py
- synapse/util/async_helpers.py
- tests/util/test_async_helpers.py
The main change here is to add a helper function `gather_optional_coroutines`, which works in a similar way as `yieldable_gather_results` but takes a set of coroutines rather than a function
> Speed up sliding sync by computing extensions in parallel

- changelog.d/17813.bugfix
- synapse/storage/databases/main/room.py
when updating the remote_media_cache table
> Remove `Generator` in `_quarantine_media_txn()`

- changelog.d/17894.misc
- synapse/http/proxy.py
- tests/http/test_matrixfederationclient.py
- tests/http/test_proxy.py
Remove usage of internal header encoding API
```py
from twisted.web.http_headers import Headers
Headers()._canonicalNameCaps
Headers()._encodeName
```
Introduced in https://github.com/matrix-org/synapse/pull/15913 <- https://github.com/matrix-org/synapse/pull/15773
(run the …
> Remove usage of internal header encoding API

- changelog.d/17887.misc
- docker/Dockerfile
As 3.13 has now been released, recent 3.12 releases should be stable enough.
> Bump Synapse Dockerfile default to Python 3.12

- changelog.d/17888.feature
- docs/admin_api/experimental_features.md
- synapse/config/experimental.py
- synapse/handlers/sync.py
- synapse/rest/admin/experimental_features.py
- synapse/rest/client/sync.py
- tests/handlers/test_sync.py
Basically, if the client sets a special query param on `/sync` v2 instead of responding with `state` at the *start* of the timeline, we instead respond with `state_after` at the *end* of the timeline. 
We do this by using the `current_state_delta_stream` table, which is actually reliable, rather than messing around with "state at" points on the timeline.
c.f. MSC4222
Reviewable commit-by-commit.
> Add experimental support for MSC4222

- changelog.d/17813.bugfix
- changelog.d/17813.misc
- changelog.d/17814.bugfix
- changelog.d/17814.misc
- changelog.d/17815.bugfix
- changelog.d/17815.misc
- changelog.d/17816.bugfix
- changelog.d/17816.misc
- changelog.d/17817.bugfix
- changelog.d/17817.misc
- changelog.d/17818.bugfix
- changelog.d/17818.misc
- changelog.d/17890.misc
Use more correct changelog entries for refactoring `Generator` usage
- https://github.com/element-hq/synapse/pull/17813
- https://github.com/element-hq/synapse/pull/17814
- https://github.com/element-hq/synapse/pull/17815
- https://github.com/element-hq/synapse/pull/17816
- https://github.com/element-hq/synapse/pull/17817
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." …
> Use more correct changelog entries for refactoring `Generator` usage

- changelog.d/17902.misc
- pyproject.toml
Update version constraint to allow the latest `poetry-core` `1.9.1`
Context:
> I am working on updating poetry-core in Fedora and synapse is one of affected packages. Please run a CI to see if it works properly. Thank you.
Mergeable version of https://github.com/element-hq/synapse/pull/17848 (original contributor @hrnciar)
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." …
> Update version constraint to allow the latest `poetry-core` `1.9.1`

- changelog.d/17903.bugfix
- synapse/handlers/e2e_keys.py
- synapse/storage/databases/main/end_to_end_keys.py
- synapse/storage/schema/main/delta/88/03_add_otk_ts_added_index.sql
- tests/handlers/test_e2e_keys.py
Currently, one-time-keys are issued in a somewhat random order. (In practice, they are issued according to the lexicographical order of their key IDs.) That can lead to a situation where a client gives up hope of a given OTK ever being used, whilst it is still on the server.
Related: https://github.com/element-hq/element-meta/issues/2356
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed …
> Issue one time keys in upload order

- changelog.d/17906.bugfix
- tests/http/server/_base.py
The latest Twisted release changed how they implemented `__await__` on deferreds, which broke the machinery we used to test cancellation.
This PR changes things a bit to instead patch the `__await__` method, which is a stable API. This mostly doesn't change the core logic, except for fixing two bugs:
- We previously did not intercept all await points
- After cancellation we now need to not only unblock currently blocked await points, but also make sure we don't block any future await  points.
c.f. https://github.com/twisted/twisted/pull/12226
> Fix cancellation tests with new Twisted. 

- .github/workflows/tests.yml
- changelog.d/17909.misc
...as those are the latest versions of Python and Postgres that Synapse supports. Technically missed in https://github.com/element-hq/synapse/pull/17752
Noticed in https://github.com/element-hq/synapse/pull/17908#discussion_r1831457002
> Switch portdb CI to python 3.13, pg 17

- changelog.d/17911.bugfix
- tests/util/test_async_helpers.py
> Fix Twisted tests with latest release

- changelog.d/17915.bugfix
- synapse/handlers/message.py
- synapse/handlers/sync.py
- synapse/rest/client/sync.py
- synapse/storage/controllers/state.py
- synapse/storage/databases/main/state.py
- synapse/storage/databases/state/bg_updates.py
- synapse/storage/databases/state/store.py
- synapse/types/state.py
- tests/handlers/test_sync.py
There was a bug that meant we would return the full state of the room on incremental syncs when using lazy loaded members and there were no entries in the timeline.
This was due to trying to use `state_filter or state_filter.all()` as a short hand for handling `None` case, however `state_filter` implements `__bool__` so if the state filter was empty it would be set to full.
c.f. MSC4222 and #17888
> Fix MSC4222 returning full state

- changelog.d/17913.doc
- docs/usage/configuration/config_documentation.md
Fixes: #17663 
Base: `develop` 
Original commit schedule, with full messages:
<ol>
<li>
Add case-by-case breakdown of `enable_authenticated_media` \
Closes #17663
</li>
</ol>
> Clarify the semantics of the `enable_authenticated_media` configuration option.

- changelog.d/17912.misc
- synapse/storage/databases/main/state_deltas.py
- synapse/storage/schema/main/delta/88/04_current_state_delta_index.sql
As we're now using it in the sync APIs to get state changes within a room
> Add index to `current_state_delta_stream`

- .github/workflows/release-artifacts.yml
- changelog.d/17921.misc
Broke in #17905 due to upgrading the `upload-artifact` action, as we didn't rename debs. I think we also need to change how we download the artefacts and attach them to a release, as they'll download to a different place.
Docs:
- https://github.com/actions/upload-artifact/tree/v4/
- https://github.com/actions/download-artifact/tree/v4/
> Fix building and attaching release artifacts

- .github/workflows/release-artifacts.yml
- changelog.d/17923.misc
We were pinned to an old version that had deprecation warnings.
In new versions of the action leaving off properties (i.e. `draft` and `prerelease`) tells the action to not modify those properties of the release.
> Unpin the upload release GHA action

- .github/workflows/release-artifacts.yml
- changelog.d/17924.misc
MacOS 12 is end-of-life and GitHub is deprecating support for it (including doing brown outs). Let's bump to MacOS 13.
> Bump macos version used to build wheels

- changelog.d/17934.feature
- synapse/handlers/e2e_keys.py
- synapse/storage/databases/main/end_to_end_keys.py
- synapse/storage/schema/main/delta/88/05_drop_old_otks.sql.postgres
- synapse/storage/schema/main/delta/88/05_drop_old_otks.sql.sqlite
- tests/handlers/test_e2e_keys.py
To work around the fact that, pre-https://github.com/element-hq/synapse/pull/17903, our database may have old one-time-keys that the clients have long thrown away the private keys for, we want to delete OTKs that look like they came from libolm.
To spread the load a bit, without holding up other background database updates, we use a scheduled task to do the work.
> Create one-off scheduled task to delete old OTKs

- changelog.d/17946.misc
- synapse/_scripts/synapse_port_db.py
- synapse/storage/databases/main/sliding_sync.py
- synapse/storage/schema/main/delta/88/05_sliding_sync_room_config_index.sql
This was due to a missing index, which meant that deleting previous connections associated with the device and `conn_id` took a long time.
> Speed up slow initial sliding syncs on large servers

- changelog.d/17932.misc
- synapse/http/client.py
This allows synapse to run with python multipart >=0.0.13 without any tricky fallback. There is a conflict between 2 packages called multipart, so this should be modified.
> Support both import names of PyPI package `python-multipart`.

- changelog.d/17945.misc
- docker/complement/conf/workers-shared-extra.yaml.j2
We've been doing manual hacks in our images to enable support for this when testing E2EE changes, but the number of bridges and bots that now expect this to be enabled is increasing, and it would make sense to have these enabled by default in the test image.
(run the …
> Add encrypted appservice extensions to Complement test image.

- changelog.d/17936.misc
- synapse/storage/schema/main/delta/88/04_current_state_delta_index.sql
Added in #17912, was a bad copy and paste.
> Fix incorrect comment in new schema delta

- changelog.d/17872.doc
- docs/openid.md
> Add Forgejo oidc provider config example

- changelog.d/17952.misc
- docs/admin_api/user_admin_api.md
- synapse/handlers/admin.py
- tests/rest/admin/test_user.py
As the title states - return whether the user is suspended when querying the user account in the Admin API.
> Return suspended status when querying user account 

- changelog.d/17933.bugfix
- synapse/federation/sender/__init__.py
- synapse/federation/sender/per_destination_queue.py
- synapse/storage/databases/main/cache.py
- synapse/storage/databases/main/events_worker.py
- tests/federation/test_federation_sender.py
For context of why we delay read receipts, see https://github.com/matrix-org/synapse/issues/4730.
Element Web often sends read receipts in quick succession, if it reloads the timeline it'll send one for the last message in the old timeline and again for the last message in the new timeline. This caused remote users to see a read receipt for older messages come through quickly, but then the second read receipt taking a while to arrive for the most recent message.
There are two things going on in this PR:
1. There was a mismatch between seconds and milliseconds, and so we ended up delaying for far longer than intended.
2. Changing the logic to reuse the `DestinationWakeupQueue` (used for presence)
The changes in logic are:
- Treat the first receipt and subsequent receipts in a room in the …
> Fix up logic for delaying sending read receipts over federation.

- changelog.d/17960.bugfix
- synapse/server.py
In a worker-mode deployment, the `E2eKeysHandler` is not necessarily loaded, which means the handler for the `delete_old_otks` task will not be registered. Make sure we load the handler.
Introduced in https://github.com/element-hq/synapse/pull/17934
> Fix `delete_old_otks` job on worker deployments

- changelog.d/17253.misc
- rust/src/rendezvous/mod.rs
This is a workaround for some proxy setup, where the ETag header gets stripped from the response headers unless there is a Content-Type header set.
In particular, we saw this bug when putting Cloudflare in front of Synapse.
I'm pretty sure this is a Cloudflare bug, as this behaviour isn't documented anywhere, and doesn't make sense whatsoever.
> MSC4108: Add a Content-Type header on the PUT response

- Cargo.lock
- changelog.d/17966.misc
- rust/Cargo.toml
- rust/src/acl/mod.rs
- rust/src/events/internal_metadata.rs
- rust/src/events/mod.rs
- rust/src/http.rs
- rust/src/lib.rs
- rust/src/push/evaluator.rs
- rust/src/push/mod.rs
- rust/src/rendezvous/mod.rs
Keep up-to-date with pyo3 releases. This bump enables Python 3.13 support and resolves deprecations.
Links for quick reference:
https://github.com/PyO3/pyo3/releases
https://github.com/davidhewitt/pythonize/releases
https://github.com/vorner/pyo3-log
(run the …
> Bump pyo3 to v0.23.2

- changelog.d/17962.misc
- synapse/replication/tcp/commands.py
- synapse/replication/tcp/handler.py
- synapse/util/task_scheduler.py
- tests/util/test_task_scheduler.py
Currently, when a new scheduled task is added and its scheduled time has already passed, we set it to ACTIVE. This is problematic, because it means it will jump the queue ahead of all other SCHEDULED tasks; furthermore, if the Synapse process gets restarted, it will jump ahead of any ACTIVE tasks which have been started but are taking a while to run.
Instead, we leave it set to SCHEDULED, but kick off a call to `_launch_scheduled_tasks`, which will decide if we actually have capacity to start a new task, and start the newly-added task if so.
> Fix new scheduled tasks jumping the queue

- changelog.d/17972.misc
- synapse/api/urls.py
- synapse/config/cas.py
- synapse/config/server.py
- synapse/rest/synapse/client/pick_idp.py
- tests/api/test_urls.py
- tests/rest/client/test_login.py
- tests/rest/client/utils.py
- tests/utils.py
Consolidate SSO redirects through `/_matrix/client/v3/login/sso/redirect(/{idpId})`
Spawning from https://github.com/element-hq/sbg/pull/421#discussion_r1859497330 where we have a proxy that intercepts responses to  `/_matrix/client/v3/login/sso/redirect(/{idpId})` in order to upgrade them to use OAuth 2.0 Pushed Authorization Requests (PAR). Instead of needing to intercept multiple endpoints that redirect to the authorization endpoint, it seems better to just have Synapse consolidate to a single flow.
1. Create a new OAuth application. I'll be using GitHub for example but there are [many options](https://github.com/matrix-org/synapse/blob/be65a8ec0195955c15fdb179c9158b187638e39a/docs/openid.md). Visit https://github.com/settings/developers -> **New OAuth App**
- Application name: …
> Consolidate SSO redirects through `/_matrix/client/v3/login/sso/redirect(/{idpId})`

- changelog.d/17975.feature
- synapse/config/experimental.py
- synapse/push/httppusher.py
- tests/push/test_http.py
This PR implements [MSC4076: Let E2EE clients calculate app badge counts themselves (disable_badge_count)](https://github.com/matrix-org/matrix-spec-proposals/pull/4076).
The MSC is not merged yet but I have not put this new code under a experimental feature flag. The behavior change is very limited to the homerserver / client / push gateway interfaces. It can only happen if the client asks for it. 
- Feel free to credit yourself, by adding …
> MSC4076: Add disable_badge_count to pusher configuration

- changelog.d/17705.feature
- synapse/appservice/__init__.py
- synapse/config/appservice.py
- synapse/handlers/device.py
- synapse/handlers/register.py
- synapse/rest/client/devices.py
- synapse/rest/client/register.py
- tests/handlers/test_appservice.py
- tests/handlers/test_oauth_delegation.py
- tests/rest/client/test_devices.py
- tests/rest/client/test_register.py
- tests/unittest.py
This is an implementation of MSC4190, which allows appservices to manage their user's devices without /login & /logout.
This can be reviewed commit by commit, as each change in behaviour has been implemented in separate commits.
> Support for MSC4190: device management for application services

- .github/workflows/release-artifacts.yml
- changelog.d/17995.misc
We are still seeing duplicate releases on v2.0.5, so roll back further. [Other](https://github.com/Poko-Apps/curl-openssl-android/commit/f8a5a60b7c4b196c703d322bb3d11e9495807426#diff-88ab30345d9874c4336fe50b54b083ba5bdd925be961c34060e6a192b56b0433R72) [repositories](https://github.com/Glistix/glistix/commit/55fca4fec74aa114faf553b563ae5883b5d76be0#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR105) seem to have settled on this version.
Addresses https://github.com/element-hq/synapse/issues/17991
We're just going to test this during 1.121.0rc1.
> Pin softprops/action-gh-release to v0.1.15

- changelog.d/17996.misc
- rust/src/identifier.rs
Adds the RoomID & EventID rust types to the rust lib.
Also adds a Deserialize impl to the existing UserID type.
> Add RoomID & EventID rust types

- changelog.d/17930.bugfix
- synapse/events/snapshot.py
When rejecting a withdrew invite through federation, an out of band event needs to be created.
When doing so with a third_party_rules module installed, `get_prev_state_ids` [is called](https://github.com/element-hq/synapse/blob/e0fdb862cbbddc920a30233024eb99038ee2fb28/synapse/module_api/callbacks/third_party_event_rules_callbacks.py#L285) on the context to calculate the state to pass at `check_event_allowed` callbacks.
The context for outliers is defined [here](https://github.com/element-hq/synapse/blob/e0fdb862cbbddc920a30233024eb99038ee2fb28/synapse/events/snapshot.py#L168), and `state_group_before_event` is None.
This change makes the behavior of `get_prev_state_ids` and `get_current_state_ids` match the one presented in the docstring regarding null state_group.
(run the …
> Fix bug when rejecting withdrew invite with a third_party_rules module

- .github/workflows/release-artifacts.yml
- changelog.d/18025.misc
This hopefully fixes https://github.com/element-hq/synapse/issues/17991, as we first upgraded to v2 and are now back to 0.1.15.
(This was lost in https://github.com/element-hq/synapse/pull/17923, related https://github.com/element-hq/synapse/pull/17995)
> Attempt to fix GHA issues

- changelog.d/17976.doc
- docs/admin_api/user_admin_api.md
This section could probably do with a lot more editorial attention, but for now this is all there is in terms of documentation. The field is already returned by Synapse: https://github.com/element-hq/synapse/blob/4587decd678300217969f1d2f69b226421a33ced/synapse/handlers/admin.py#L150
`last_seen_ts` was introduced in https://github.com/matrix-org/synapse/pull/16218
- Feel free to credit yourself, by adding a sentence "Contributed by …
> Add `last_seen_ts` to query user example

- changelog.d/17849.feature
- docs/usage/configuration/config_documentation.md
- synapse/config/emailconfig.py
- synapse/handlers/send_email.py
- tests/handlers/test_send_email.py
The existing `email.smtp_host` config option is used for two distinct purposes: it is resolved into the IP address to connect to, and used to (request via SNI and) validate the server's certificate if TLS is enabled.  This new option allows specifying a different name for the second purpose.
This is especially helpful, if `email.smtp_host` isn't a global FQDN, but something that resolves only locally (e.g. "localhost" to connect through the loopback interface, or some other internally routed name), that one cannot get a valid certificate for.
Alternatives would of course be to specify a global FQDN as `email.smtp_host`, or to disable TLS entirely, both of which might be undesirable, depending on the SMTP server configuration.
- Be a short description of your change which makes sense to …
> Add email.tlsname config option

- changelog.d/17998.misc
- synapse/http/client.py
- synapse/http/proxyagent.py
- synapse/http/replicationagent.py
- tests/http/test_proxyagent.py
Fixes various `mypy` errors associated with Twisted `24.11.0`.
Hopefully addresses https://github.com/element-hq/synapse/issues/17075, though I've yet to test against `trunk`.
Changes should be compatible with our currently pinned Twisted version of `24.7.0`.
> Fix mypy errors on Twisted 24.11.0

- changelog.d/17994.doc
- docker/conf-workers/nginx.conf.j2
- docs/reverse_proxy.md
Update reverse proxy docs with what we've learned from https://github.com/element-hq/synapse/pull/17986
Also vice versa and update our nginx config with what I learned from the reverse proxy docs.
(run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run- …
> Update reverse proxy docs with what we've learned from #17986

- changelog.d/18017.misc
- synapse/storage/databases/main/purge_events.py
This is already done for `purge_history` but seems to have been forgotten for `purge_room`.
> Disable statement timeout during room purge

- .ci/scripts/calculate_jobs.py
- .github/workflows/tests.yml
- changelog.d/18034.removal
- docs/upgrade.md
- synapse/storage/engines/postgres.py
This is essentially matrix-org/synapse#14392. I didn't see anything in there about updating sytest or complement.
The main driver of this is so that I can use `jsonb_path_exists` in #17488. 😄 
(run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the- …
> Remove support for PostgreSQL 11 and 12

- changelog.d/18020.misc
- contrib/cmdclient/console.py
- contrib/cmdclient/http.py
- synapse/logging/scopecontextmanager.py
- synapse/util/patch_inline_callbacks.py
`defer.returnValue` was only needed in Python 2; in Python 3, a simple `return` is fine.
`twisted.internet.defer.returnValue` is deprecated as of Twisted 24.7.0.
Most uses of `returnValue` in synapse were removed a while back; this cleans up some remaining bits.
(run the …
> Stop using twisted.internet.defer.returnValue

- changelog.d/18029.bugfix
- synapse/handlers/admin.py
> Make admin api redactions use the requester to send the redaction

- changelog.d/18043.bugfix
- tests/rest/admin/test_user.py
A test for https://github.com/element-hq/synapse/pull/18029.
> Add a test to verify remote user messages can be redacted via admin api redaction endpoint if requester is admin in room

- changelog.d/18063.misc
- synapse/api/constants.py
- synapse/handlers/profile.py
- synapse/handlers/sso.py
- synapse/handlers/user_directory.py
- synapse/module_api/__init__.py
- synapse/rest/client/profile.py
Refactor `get_profile` to avoid returning "empty" (`None` / `null`) fields. Currently this is not very important, but will be more useful once #17488 lands. It does update the servlet to use this now which has a minor change in behavior: additional fields served over federation will now be properly sent back to clients.
It also adds constants for `avatar_url` / `displayname` although I did not attempt to use it everywhere possible.
- Feel …
> Refactor get_profile: do not return missing fields.

- changelog.d/18052.removal
- synapse/config/experimental.py
- synapse/rest/client/reporting.py
- synapse/rest/client/versions.py
It's been rotated out of known clients, and should be safe for removal now.
Fixes https://github.com/element-hq/synapse/issues/17373
> Drop unstable MSC4151 implementation

- changelog.d/18035.feature
- docs/admin_api/rooms.md
- synapse/rest/admin/rooms.py
- tests/rest/admin/test_room.py
Adds a query param `type` to `/_synapse/admin/v1/rooms/{room_id}/state` that filters the state event query by state event type.
> Add the ability to filter by state event type on admin room state endpoint

- changelog.d/18091.bugfix
- synapse/storage/background_updates.py
Otherwise these can race with other long running queries and lock out all other queries.
This caused problems in v1.22.0 as we added an index to `events` table in #17948, but that got interrupted and so next time we ran the background update we needed to delete the half-finished index. However, that got blocked behind some long running queries and then locked other queries out (stopping workers from even starting).
> Drop indices concurrently on background updates

- changelog.d/18064.doc
- docs/usage/configuration/config_documentation.md
Document possibility of configuring `tls` for a worker instance in `instance_map`
https://github.com/element-hq/synapse/blob/ebc21a8c67ed7a05af010e329b6402cd41229ebe/synapse/config/workers.py#L281-L284
https://github.com/element-hq/synapse/blob/ebc21a8c67ed7a05af010e329b6402cd41229ebe/synapse/config/workers.py#L330-L336
https://github.com/element-hq/synapse/blob/ebc21a8c67ed7a05af010e329b6402cd41229ebe/synapse/config/workers.py#L140
https://github.com/element-hq/synapse/blob/ebc21a8c67ed7a05af010e329b6402cd41229ebe/synapse/config/workers.py#L110-L115
- Use markdown where necessary, …
> Document possibility of configuring `tls` for a worker instance in `instance_map`

- changelog.d/18112.bugfix
- synapse/config/_base.py
Raise an error if someone is using an incorrect suffix in a config duration string.
Previously, a value like `5q` would be interpreted as 5 milliseconds. We should just raise an error instead of letting someone run with a misconfiguration.
(run the …
> Raise an error if someone is using an incorrect suffix in a config duration string

- changelog.d/18119.bugfix
- synapse/storage/databases/main/room.py
This is so workers can call these functions.
This was preventing the [Delete Room Admin API](https://element-hq.github.io/synapse/latest/admin_api/rooms.html#version-2-new-version) from succeeding when `block: true` was specified. This was because we had `run_background_tasks_on` configured to run on a separate worker.
As workers weren't able to call the `block_room` storage function before this PR, the (delete room) task failed when taken off the queue by the worker.
> Allow (un)block_room storage functions to be called on workers

- changelog.d/18141.bugfix
- synapse/state/__init__.py
- synapse/storage/databases/state/deletion.py
- tests/rest/client/test_rooms.py
Regressed as part of https://github.com/element-hq/synapse/pull/18107
This does two things:
1. Only check if the state groups have been deleted when calculating the event context (as that's when we will insert them). This avoids lots of checks for read operations.
2. Don't lock the `state_groups` rows when doing the check. This adds overhead, and it doesn't prevent any races.
> Fix performance of `check_state_groups_and_bump_deletion`

- changelog.d/18145.bugfix
- changelog.d/18145.misc
- demo/start.sh
Missed in https://github.com/element-hq/synapse/pull/18000
> Add `rc_presence` ratelimiting config to demo/start.sh

- changelog.d/18125.bugfix
- synapse/handlers/auth.py
When updating 3pid for a user email from admin api and sending invalid email the server throws 500 internal server error.
changed to 400 Bad request and returned the error message
> Fix internal server error when updating 3pid address with invalid email

- changelog.d/18124.misc
- synapse/handlers/worker_lock.py
This is to help track down a possible, but very rare, worker deadlock that was seen on matrix.org.
In theory, you could work back from an instance of these new logs to the approximate time when the lock was obtained and focus the diagnostic efforts there.
(run the …
> Add log message when worker lock timeouts get large

- changelog.d/18159.doc
- docs/usage/configuration/config_documentation.md
`burst_count` is an int, so 0.5 is floored to 0. Set it to 0 instead.
Found by @bjoe2k4 in [this comment](https://github.com/element-hq/synapse/pull/18000#discussion_r1953462063).
> Update `rc_presence` config docs with int burst_count

- changelog.d/18138.doc
- docs/usage/configuration/config_documentation.md
Document consequences of replacing secrets. The covered config options are `registration_shared_secret`, `macaroon_secret_key`, `form_secret` and `worker_replication_secret`.
Even though I looked at the source code to check the added documentation is right, I would appreciate additional verification of the statements made.
In an hand-wavy attempt at classifying how bad the consequences of secret replacement are, I added some explanations as warnings and others as regular paragraphs.
Closes #17971 
- End with either a period (.) …
> Document consequences of replacing secrets

- changelog.d/18172.misc
- synapse/storage/databases/main/user_directory.py
If a user search has many words we can end up creating really large queries that take a long time for the database to process. Generally, such searches don't return any results anyway (due to limits on user ID and display name length).
We "fix" this by cheating and only searching for the first ten words.
> Limit size of user directory search queries

- changelog.d/18144.feature
- synapse/module_api/__init__.py
- Add `get_current_time_msec()` method to the [module API](https://matrix-org.github.io/synapse/latest/modules/writing_a_module.html) for sound time comparisons with Synapse.
- Fixes #18104 
(run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-li …
> Add method to get current server time in milliseconds in ModuleApi

- changelog.d/18162.misc
- docs/admin_api/user_admin_api.md
Missed in the transition from experimental to stable. 
Fixes #18160
> Document suspension Admin API

- changelog.d/18177.feature
- docs/usage/configuration/config_documentation.md
- synapse/config/oidc.py
- synapse/handlers/oidc.py
- tests/handlers/test_oidc.py
Add support for overriding `id_token_signing_alg_values_supported` for an OpenID identity provider.
Normally, when `discovery` is enabled, `id_token_signing_alg_values_supported` comes from the OpenID Discovery Document (`/.well-known/openid-configuration`). If nothing was specified, we default to supporting `RS256` in the downstream usage.
This PR just adds support for adding a default/overriding the the discovered value [just like we do for other things like the `token_endpoint`](https://github.com/element-hq/synapse/blob/1525a3b4d48a0f5657d61423e1f205bff9a77948/docs/usage/configuration/config_documentation.md#oidc_providers), etc.
```
poetry run trial tests.handlers.test_oidc.OidcHandlerTestCase
```
- Be a short description of your change which makes sense to users. "Fixed a bug that …
> Add support for overriding `id_token_signing_alg_values_supported` for an OpenID identity provider

- changelog.d/18175.misc
- docker/complement/conf/workers-shared-extra.yaml.j2
- docker/conf/homeserver.yaml
- docs/upgrade.md
- docs/usage/configuration/config_documentation.md
- synapse/config/room_directory.py
- tests/handlers/test_directory.py
- tests/handlers/test_room_list.py
- tests/rest/admin/test_room.py
- tests/rest/client/test_rooms.py
This is in line with our general policy of ensuring that the default config is reasonably locked down.
SyTest PR to fix tests: https://github.com/matrix-org/sytest/pull/1396
> Disable room list publication by default

- changelog.d/18152.doc
- docs/admin_api/user_admin_api.md
Previously it was in the middle of the parameter definitions.
> Move User Event Redaction Admin API version indicator to the correct place

- changelog.d/18191.feature
- docs/usage/configuration/config_documentation.md
- synapse/config/workers.py
- tests/config/test_load.py
Workers now get their secrets from files, too! There are not many config options left to pathify :) Includes documentation and unit tests.
> Add worker_replication_secret_path config option

- changelog.d/18197.feature
- docs/usage/configuration/config_documentation.md
- synapse/config/oidc.py
- synapse/handlers/oidc.py
- tests/handlers/test_oidc.py
Allows overriding the `redirect_uri` parameter sent to both the authorization and token endpoints of the IdP. Typically this parameter is hardcoded to `<public_baseurl>/_synapse/client/oidc/callback`.
Yet it can be useful in certain contexts to allow a different callback URL. For instance, if you would like to intercept the authorization code returned from the IdP and do something with it, before eventually calling Synapse's OIDC callback URL yourself.
This change enables enterprise use cases but does not change the default behaviour.
---
Best reviewed commit-by-commit.
> Add `redirect_uri` option to `oidc_providers` entries

- changelog.d/18174.misc
- synapse/api/auth/msc3861_delegated.py
- tests/handlers/test_oauth_delegation.py
The context for this is that the Matrix spec allows basically anything in the device ID. With MSC3861, we're restricting this to strings that can be represented as scopes.
Whilst this works well for next-gen auth sessions, compatibility/legacy sessions still can have characters that can't be encoded (mainly spaces) in them.
To work around that, we added in MAS a behaviour where the device_id is given as an explicit property of the token introspection response, and remove it from the scope.
Because we don't expect users to rollout new Synapse and MAS versions in sync, we needed a way to 'advertise' support for this behaviour: the easiest way to do that was through an extra header in the introspection response.
On the longer term, I expect MAS and Synapse to move away from the introspection …
> Support getting the device ID explicitly from MAS

- .ci/before_build_wheel.sh
- changelog.d/18212.misc
- pyproject.toml
Without this, we get the following error when building for 32-bit i686 Linux:
```
Running before_all...
+ /opt/python/cp38-cp38/bin/python -c 'import sys, json, os; json.dump(os.environ.copy(), sys.stdout)'
+ sh -c 'curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.82.0 -y --profile minimal'
info: downloading installer
warn: Not enforcing strong cipher suites for TLS, this is potentially less secure
/tmp/tmp.KlFNNCWiwj/rustup-init: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
✕ 1.30s
Error: Command ['sh', '-c', 'curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.82.0 -y --profile minimal'] failed with code 1. 
```
There may be other platforms where this is relevant, too. (libatomic provides …
> Fix wheel building configuration in CI by installing libatomic1.

- changelog.d/18211.misc
- scripts-dev/release.py
If one workflow is successful and one fails, currently that is reported as success.
> Fix detection of workflow failures in the release script.

- changelog.d/18235.misc
- synapse/media/_base.py
- synapse/media/media_repository.py
- synapse/media/thumbnailer.py
- tests/federation/test_federation_media.py
- tests/rest/client/test_media.py
We do a few things in this PR to better support caching:
1. Change `Cache-Control` header to allow intermediary proxies to cache media *only* if they revalidate on every request. This means that the intermediary cache will still send the request to Synapse but with a `If-None-Match` header, at which point Synapse can check auth and respond with a 304 and empty content.
2. Add `ETag` response header to all media responses. We hardcode this to `1` since all media is immutable (beyond being deleted).
3. Check for `If-None-Match` header (after checking for auth), and if it matches then respond with a 304 and empty body.
> Add caching support to media endpoints

- .github/workflows/docker.yml
- .github/workflows/docs-pr-netlify.yaml
- .github/workflows/docs-pr.yaml
- .github/workflows/docs.yaml
- .github/workflows/fix_lint.yaml
- .github/workflows/latest_deps.yml
- .github/workflows/poetry_lockfile.yaml
- .github/workflows/push_complement_image.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/tests.yml
- .github/workflows/triage-incoming.yml
- .github/workflows/triage_labelled.yml
- .github/workflows/twisted_trunk.yml
- changelog.d/18255.misc
After the [recent supply chain attack](https://www.wiz.io/blog/new-github-action-supply-chain-attack-reviewdog-action-setup) in `tj-actions/changed-files` and actions based on it, it's become clear that relying on git tags to pin our dependencies is not enough (as tags can simply be replaced). Therefore we need to switch to hashes.
Dependabot should continue to update these dependencies for us.
Best reviewed commit-by-commit. Though if CI passes, we're *probably* fine.
> Pin our GitHub Actions dependencies

- changelog.d/18271.docker
- docker/Dockerfile
Do this instead of appending package names with ":{arch}", which fails when downloading architecture-independent packages for a non-host arch.
> Dockerfile: set package arch via APT config option

- changelog.d/18283.doc
- docs/development/dependencies.md
Add docs for how to clear out the Poetry wheel cache
As shared by @reivilibre, https://github.com/element-hq/synapse/pull/18261#issuecomment-2754607816
Relevant Poetry issue around how this should be handled by them: https://github.com/python-poetry/poetry/issues/10304
(run the …
> Add docs for how to clear out the Poetry wheel cache

- changelog.d/18284.misc
- synapse/storage/schema/state/delta/90/03_remove_old_deletion_bg_update.sql
This background DB delta removes the old state group deletion background update from the `background_updates` table if it exists.
The `delete_unreferenced_state_groups_bg_update` update should only exist in that table if a homeserver ran v1.126.0rc1/v1.126.0rc2, and rolled back or forward to any other version of Synapse before letting the update finish.
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." …
> Add DB delta to remove the old state group deletion job

- changelog.d/18277.feature
- synapse/media/media_repository.py
- synapse/media/media_storage.py
- synapse/storage/databases/main/media_repository.py
- synapse/storage/databases/main/room.py
- synapse/storage/databases/main/user_directory.py
- synapse/storage/schema/__init__.py
- synapse/storage/schema/main/delta/91/01_media_hash.sql
- tests/handlers/test_profile.py
- tests/media/test_media_retention.py
- tests/media/test_media_storage.py
- tests/rest/admin/test_admin.py
- tests/rest/admin/test_media.py
- tests/rest/client/test_media.py
- tests/rest/media/test_domain_blocking.py
- tests/test_utils/__init__.py
This PR makes a few radical changes to media. This now stores the SHA256 hash of each file stored in the database (excluding thumbnails, more on that later). If a set of media is quarantined, any additional uploads of the same file contents or any other files with the same hash will be quarantined at the same time.
Currently this does NOT:
- De-duplicate media, although a future extension could be to do that.
- Run any background jobs to identify the hashes of older files. This could also be a future extension, though the value of doing so is limited to combat the abuse of recent media.
- Hash thumbnails. It's assumed that thumbnails are parented to some form of media, so you'd likely be wanting to quarantine the media and the thumbnail at the same time.
This needs further refinement, but …
> Store hashes of media files, and allow quarantining by hash.

- changelog.d/18225.doc
- docs/usage/administration/admin_faq.md
Riot is now known as element and Access token moved to Help & About
> Update admin_faq - Fix how to obtain access token

- changelog.d/18296.doc
- docs/admin_api/media_admin_api.md
Essentially document the change in behaviour in #18277 
> Document media hashing changes

- changelog.d/18231.feature
- synapse/api/auth/msc3861_delegated.py
- tests/handlers/test_oauth_delegation.py
Evolution of https://github.com/element-hq/synapse/commit/cd78f3d2ee15ccf3e8229a1f529e0e2c16e15c45
This cache does not have any explicit invalidation, but this is deemed acceptable (see code comment).
We may still prefer to add it eventually, letting us bump up the Time-To-Live (TTL) on the cache as we currently set a 2 minute expiry
to balance the fact that we have no explicit invalidation.
This cache makes several things more efficient:
- reduces number of outbound requests from Synapse, reducing CPU utilisation + network I/O
- reduces request handling time in Synapse, which improves client-visible latency
- reduces load on MAS and its database
---
Other than that, this PR also introduces support for `expires_in` (seconds) on the introspection response.
This lets the cached responses …
> Add an access token introspection cache to make Matrix Authentication Service integration (MSC3861) more efficient.

- changelog.d/18274.docker
- docker/prefix-log
- Explicitly use `mawk` instead of `awk`, since an extension of the former is used
- Use `fflush` to reduce interleaving the output of different processes & streams
- Move the `mawk` command to a shell function, instead of writing it twice
- Look up the  `SUPERVISOR_PROCESS_NAME` environment variable in `mawk`, instead of reading it in the shell & using complex quoting to pass it to `mawk`
- Feel free to credit yourself, by adding a sentence …
> Tweaks to prefix-log

- changelog.d/18302.feature
- synapse/storage/databases/main/media_repository.py
- synapse/storage/schema/main/delta/91/01_media_hash.sql
Uses the same newsfile contents as https://github.com/element-hq/synapse/pull/18277.
> Make sure media hashes are not queried until the index is up

- changelog.d/18294.docker
- docker/complement/Dockerfile
The base postgres image already has the /var/run/postgresql directory, and COPY can set file ownership with chown=, so COPY it instead of making it from scratch & manually setting its ownership.
(run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-th …
> complement-synapse: COPY existing dir from base

- changelog.d/18334.bugfix
- synapse/api/auth/msc3861_delegated.py
This is a copy of what we do for internal auth, and we should figure out a way to deduplicate some of this stuff:
https://github.com/element-hq/synapse/blob/dd05cc55eedbf086ae224a13c9ae9f0332d96b1f/synapse/api/auth/internal.py#L62-L110
> Fix `force_tracing_for_users` config when using MAS

- changelog.d/18345.bugfix
- synapse/storage/databases/main/roommember.py
Follow on from #18068
Currently the subquery in `UPDATE` is pointless, as it will still just update all `room_membership` rows. Instead, we should look at the current membership event ID (which is easily retrieved from `local_current_membership`). We also add a `AND NOT participant` to noop the `UPDATE` when the `participant` flag is already set.
cc @H-Shay
> Fix query for room participation

- changelog.d/18355.feature
- docs/workers.md
- synapse/rest/client/devices.py
We can't move PUT/DELETE as they do need to happen on main process (due to notification of device changes).
> Move GET /devices/ off main process

- changelog.d/18360.misc
- docs/workers.md
- synapse/app/generic_worker.py
- synapse/rest/admin/__init__.py
Tested by https://github.com/matrix-org/sytest/pull/1400
> Allow /rooms/ admin API to be on workers

- changelog.d/18363.bugfix
- synapse/push/httppusher.py
- tests/push/test_http.py
This fixes a bug where if a pusher gets told about a new event to push it will ignore the backoff and immediately retry sending any pending push.
> Do not retry push during backoff period

- changelog.d/18373.misc
- synapse/storage/schema/__init__.py
- synapse/storage/schema/main/delta/92/01_remove_trigger.sql.postgres
- synapse/storage/schema/main/delta/92/01_remove_trigger.sql.sqlite
See #18260
This is useful for anyone who tried Synapse v1.129.0rc1 out
Fixes #18349
To test:
- checkout v1.129.0rc1 and start
- check that the events table has the trigger (`\dS events` with postgres)
- checkout this PR and start
- check that the events table doesn't have the trigger anymore
> Remove the trigger added in #18260 and then reverted

- changelog.d/18292.docker
- docker/Dockerfile-workers
- Use a `uv:python` image for the first build layer, to reduce the number of intermediate images required, as the
main Dockerfile uses that image already
- Use a cache mount for `apt` commands
- Skip a pointless install of `redis-server`, since the redis Docker image is copied from instead
- Move some RUN steps out of the final image layer & into the build layer
Depends on https://github.com/element-hq/synapse/pull/18275
- Feel free to …
> Optimize `Dockerfile-workers`

- changelog.d/18291.docker
- docker/configure_workers_and_start.py
Use absolute path for python in script shebang, and invoke child python processes with sys.executable. This is consistent with the absolute path used to invoke python elsewhere (like in the supervisor config).
(run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_gu …
> configure_workers_and_start.py: unify python path

- changelog.d/18377.doc
- docker/configure_workers_and_start.py
- docs/upgrade.md
- docs/workers.md
Add  ^/_matrix/federation/v1/event/ to list of delegatable endpoints.
Contributed by @spaetz.
> docs/workers.md: Add  ^/_matrix/federation/v1/event/ to list of delegatable endpoints

- changelog.d/18374.misc
- synapse/handlers/oidc.py
- tests/handlers/test_oidc.py
- tests/test_utils/oidc.py
It doesn't appear necessary to check this value if we don't end up actually using the data it refers to.
This was motivated by our work against the TI-Messenger spec. In our setup, we're receiving the ID Token from the upstream IdP, yet it has an invalid `at_hash` field. We're currently communicating with the IdP's maintainers as to why this is.
In the meantime, we've theorised that checking this field isn't actually necessary in our case. Synapse only uses the access token for fetching user metadata from a separate endpoint:
https://github.com/element-hq/synapse/blob/b3099da71182feebf4fda2ec9eccf7bbffa05143/synapse/handlers/oidc.py#L837-L856
But we don't do this in our setup, as all the user's metadata is included in the ID Token itself. Thus, we never actually use the access token, and …
> Don't check the `at_hash` (access token hash) in OIDC ID Tokens if we don't use the access token

- changelog.d/18313.misc
- docs/workers.md
- synapse/app/generic_worker.py
- synapse/app/homeserver.py
- synapse/handlers/set_password.py
- synapse/rest/__init__.py
- synapse/rest/admin/__init__.py
- synapse/rest/admin/devices.py
- synapse/storage/databases/main/end_to_end_keys.py
- synapse/storage/databases/main/registration.py
This should be reviewed commit by commit.
It adds a few admin servlets that are used by MAS when in delegation mode to workers
This is lacking documentation, but we need this for the m.org migration
> Allow a few admin APIs used by MAS to run on workers

- changelog.d/18390.misc
- tests/rest/client/test_login.py
authlib 1.5.2 now single-quotes error messages in the claims, causing three tests to fail.
Replace the comparison with a regex that accepts both single or double quotes.
This succeeds the tests with both authlib 1.5.1 and 1.5.2.
See https://github.com/NixOS/nixpkgs/pull/402797 for context.
(run the …
> make tests tolerant to authlib 1.5.2 error messages

- changelog.d/18286.doc
- docs/usage/configuration/config_documentation.md
Contributing as a Nordeck employee, see source branch.
> Fix room_list_publication_rules docs for v1.126.0

- changelog.d/18439.bugfix
- synapse/storage/databases/main/sliding_sync.py
- synapse/storage/schema/main/delta/92/03_ss_membership_snapshot_idx.sql
- synapse/storage/schema/main/delta/92/04_ss_membership_snapshot_idx.sql
Follow on from #18375. This prevents blocking startup on creating the index, which can take a while
> Move index creation to background update

- changelog.d/18447.bugfix
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/schema/main/delta/92/05_fixup_max_depth_cap.sql
- synapse/types/storage/__init__.py
- tests/storage/test_events_bg_updates.py
Synapse previously did not correctly cap the max depth of an event to the max canonical json int. This can cause ordering issues for any events that were sent locally at the time.
This background update goes and correctly caps the topological ordering to the new `MAX_DEPTH`.
c.f. GHSA-v56r-hwv5-mxg6
> Fix up the topological ordering for events above `MAX_DEPTH`

- changelog.d/18454.misc
- docs/usage/configuration/config_documentation.md
- synapse/config/sso.py
- tests/handlers/test_oidc.py
Note: the use case for this was driven by OIDC login, but this change applied to all SSO login types.
The final portion of OIDC login involves receiving an `id_token` and `access_token` from the Identity Provider. If configured, the `id_token` will contain metadata about the user (such as their `family_name`, `email`, etc.) in addition to the usual `sub` (unique third-party identifier) fields.
Internally we had a use case for an enterprise customer where we wanted to require that certain claims were present in the `id_token`. We don't care what the field's *value* was, just that the field is present. If it's not present, Synapse should abort the login attempt.
This wasn't possible with Synapse today, as while Synapse does allow you to abort a login if certain fields don't have the correct …
> Allow only requiring a field be present in an SSO response, rather than specifying a required value

- Cargo.lock
- changelog.d/18460.misc
- rust/Cargo.toml
Also bump pythonize from 0.23.0 to 0.24.0, otherwise we couldn't compile as pythonize 0.23.0 required pyo3 "^0.23.0".
Addresses [RUSTSEC-2025-0020](https://rustsec.org/advisories/RUSTSEC-2025-0020), although Synapse is not affected as we don't make use of `PyString::from_object`.
[pyo3 0.24.x](https://github.com/PyO3/pyo3/releases/tag/v0.24.0) include some performance optimisations apparently, and no breaking changes.
- Feel free to credit …
> Bump pyo3 from 0.23.5 to 0.24.2

- changelog.d/18459.misc
- poetry.lock
Bumps tornado 6.5.0 to mitigate [CVE-2025-47287](https://nvd.nist.gov/vuln/detail/CVE-2025-47287).
This dependency is only used indirectly through our sentry dependency.
> Bump Tornado from 6.4.2 to 6.5.0

- changelog.d/18486.feature
- docs/modules/spam_checker_callbacks.md
- docs/spam_checker.md
- synapse/handlers/room.py
- synapse/module_api/callbacks/spamchecker_callbacks.py
- tests/module_api/test_spamchecker.py
This PR adds an additional `room_config` argument to the `user_may_create_room` spam checker module API callback.
It will continue to work with implementations of `user_may_create_room` that do not expect the additional parameter.
A side affect is that on a room upgrade the spam checker callback is called *after* doing some work to calculate the state rather than before. However, I hope that this is acceptable given the relative infrequency of room upgrades.
- Start with …
> Pass room_config argument to user_may_create_room spam checker module callback

- changelog.d/18510.misc
- contrib/grafana/synapse.json
Distinguish all vs local events being persisted in the "Event Send Time Quantiles" graph in Grafana
Before | After (notice the green dots for local events)
--- | ---
As discovered by @devonh, we use `synapse_storage_events_persisted_events_total` (which tracks *all* persisted events) for the "Events" rate in the "Event Send Time Quantiles" graph. This is pretty misleading as I would expect it to be the rate of events being sent given the graph title, "Event Send Time Quantiles".
Since the event persistence queues are shared for local and remote events from federation and will block local events being sent, I think it does still make sense to have the event persist rate. I've updated the graph to include the rate of "Local events being persisted" and the rate of "All events being …
> Distinguish all vs local events being persisted in the "Event Send Time Quantiles" graph

- changelog.d/18513.bugfix
- docs/modules/ratelimit_callbacks.md
- synapse/api/ratelimiting.py
- synapse/module_api/__init__.py
- synapse/module_api/callbacks/ratelimit_callbacks.py
- synapse/storage/databases/main/room.py
- tests/api/test_ratelimiting.py
This should have been part of https://github.com/element-hq/synapse/pull/18458 and allows for a module to do:
```python
from synapse.module_api import RatelimitOverride
```
> Export RatelimitOverride from ModuleApi

- changelog.d/18484.bugfix
- synapse/config/federation.py
- synapse/federation/sender/__init__.py
> Remove destinations from sending if not whitelisted

- changelog.d/18521.feature
- synapse/appservice/scheduler.py
- synapse/rest/client/appservice_ping.py
- tests/appservice/test_scheduler.py
Fixes https://github.com/element-hq/synapse/issues/14240
This scratches an itch that i've had for years. We regularly run into the issue where (especially in development) appservices can go down for a period and them come back up. The ping endpoint was introduced some time ago which means Synapse can determine if an AS is up more or less immediately, so we might as well use that to schedule transaction redelivery.
I believe transaction scheduling logic is largely implementation specific, so we should be in the clear to do this without any spec changes.
- Use markdown where necessary, …
> Recover an appservice if a successful ping occurs.

- changelog.d/18534.bugfix
- synapse/state/v2.py
- tests/state/test_v2.py
> bugfix: ensure _get_power_level_for_sender works when there is no PL event

- changelog.d/18543.bugfix
- synapse/app/phone_stats_home.py
- synapse/handlers/worker_lock.py
- synapse/util/constants.py
Fix a small typo I came across.
It appears the only issue this would cause is logging "Lock timeout is getting excessive" unnecessarily in a few cases before `self._retry_interval` built up.
```
>>> 5 * 2 ^ 7
13
```
> Fix typo of Math.pow, `^` -> `**`

- changelog.d/18545.bugfix
- synapse/api/auth/base.py
- synapse/event_auth.py
- synapse/push/bulk_push_rule_evaluator.py
- synapse/rest/client/room.py
- synapse/state/__init__.py
The create event is required if there is no PL event, in which case the creator gets PL100.
> bugfix: assert we always pass the create event to get_user_power_level

- Cargo.lock
- changelog.d/18578.misc
- rust/Cargo.toml
Updates `pyo3` to version 0.25.1 and, accordingly, `pyo3-log` to v0.12.4 and `pythonize` to v0.25.0.
PyO3 v0.25 enables Python 3.14 support.
> Update PyO3 to version 0.25

- Cargo.lock
- changelog.d/18600.misc
- synapse/http/additional_resource.py
- synapse/http/server.py
- synapse/rest/consent/consent_resource.py
- synapse/rest/synapse/client/federation_whitelist.py
- synapse/rest/synapse/client/jwks.py
- synapse/rest/synapse/client/new_user_consent.py
- synapse/rest/synapse/client/oidc/backchannel_logout_resource.py
- synapse/rest/synapse/client/oidc/callback_resource.py
- synapse/rest/synapse/client/password_reset.py
- synapse/rest/synapse/client/pick_idp.py
- synapse/rest/synapse/client/pick_username.py
- synapse/rest/synapse/client/rendezvous.py
- synapse/rest/synapse/client/saml2/response_resource.py
- synapse/rest/synapse/client/sso_register.py
- synapse/rest/synapse/client/unsubscribe.py
- synapse/rest/well_known.py
- tests/test_server.py
As that appears in the module API.
Broke in #18595.
> Fix backwards compat for `DirectServeJsonResource`

- changelog.d/18573.misc
- synapse/storage/database.py
It came up that this was somewhat confusing and an example might help.
So here's an example :)
> Improve docstring on `simple_upsert_many`.

- changelog.d/18594.bugfix
- synapse/api/auth/internal.py
- synapse/api/errors.py
- synapse/rest/client/login.py
- tests/rest/admin/test_user.py
Discussed in the [Synapse Dev room](https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$K4UojQtvaSpxSe35TWFXtKWGoAuHwHFcKo8qn2lwxSs?via=matrix.org&via=element.io&via=envs.net)
> Forbid locked users from using `POST /login`

- .gitignore
- changelog.d/18623.misc
Prevents local modifications to [the Zed Editor](https://zed.dev/) from appearing in unstaged git changes.
> Add `.zed/` to `.gitignore`

- .github/workflows/release-artifacts.yml
- changelog.d/18618.misc
- pyproject.toml
This takes down the CI time to build wheels from 50 minutes to <10 minutes.
**It also fixes macOS ARM builds, and includes more ARM builds in general** (we were ignoring pypy and musl before). This doesn't cost much for us to do this, reasons for not doing this is 1. space on PyPI and 2. keeping them 'officially' supported?
This is the list of wheels this built (`+` are the ones added):
```diff
matrix_synapse-1.133.0-cp39-abi3-macosx_10_9_x86_64.whl
+ matrix_synapse-1.133.0-cp39-abi3-macosx_11_0_arm64.whl
matrix_synapse-1.133.0-cp39-abi3-manylinux_2_28_aarch64.whl
matrix_synapse-1.133.0-cp39-abi3-manylinux_2_28_x86_64.whl
+ matrix_synapse-1.133.0-cp39-abi3-musllinux_1_2_aarch64.whl
matrix_synapse-1.133.0-cp39-abi3-musllinux_1_2_x86_64.whl …
```
> Use native arm runners for building wheels

- changelog.d/18672.misc
- synapse/storage/util/id_generators.py
By ensuring we don't do a no-op `UPDATE`, as this causes new tuples to be written in postgres.
> Speed up inserting into stream_positions

- changelog.d/18622.misc
- synapse/media/preview_html.py
> Update URL Preview code to work with `lxml` 6.0.0

- changelog.d/18684.feature
- docs/usage/configuration/config_documentation.md
- schema/synapse-config.schema.yaml
Correct version that `recaptcha_{private,public}_key_path` config options were introduced
Introduced in https://github.com/element-hq/synapse/pull/17984
I already see a [`v1.134.0rc1`](https://github.com/element-hq/synapse/releases/tag/v1.134.0rc1) tag from 5 days ago so I assume https://github.com/element-hq/synapse/pull/17984 will actually ship in the next release (which will be `v1.135.0`)
- Feel free to credit yourself, by adding a …
> Correct version that `recaptcha_{private,public}_key_path` config options were introduced

- changelog.d/18675.feature
- synapse/rest/client/room.py
- tests/rest/client/test_rooms.py
> Include `event_id` when getting state with `?format=event`

- changelog.d/18696.bugfix
- synapse/handlers/profile.py
According to the [Matrix c2s spec](https://spec.matrix.org/v1.2/client-server-api/#profiles), returning code 403 is allowed when querying a user profile.
When remote Synapse server admins choose to set ` allow_profile_lookup_over_federation: false`, your local synapse would send error 502 when a profile is queried over federation during Invitation (and no shared room exists yet). This would cause the Element client to error out without any possibility to recover.
Although there exists a workaround for element (not necessary with some other clients), this is unfortunately not the default.
Fixes #18425 
Fixes #18280 
Fixes #18504
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method …
> Allow return code 403 when fetching profile via federation

- changelog.d/18726.bugfix
- synapse/rest/__init__.py
- synapse/rest/client/thread_subscriptions.py
The MSC4306 endpoints were never registered, and thus never made available, even if the experimental feature flag was enabled.
> MSC4306: register the thread subscriptions servlet in the client servlet section

- changelog.d/18727.misc
- poetry.lock
- pyproject.toml
Distro packagers have been consulted and as far as has been answered so far, the lowest version of Twisted on the distros' platforms is 22.1, so this bump should be safe.
This gives us 2 notable things:
- contextvar propagation support, which would let us remove A LOT of logcontext machinery
and vastly simplify logcontext rules!
- The test helpers have moved to the new location, so no longer will you import test helpers
from the 'correct' (non-deprecated) path and get told by CI (olddeps) that your test
doesn't exist.
Changelog entries for those are reproduced below:
> - twisted.internet.defer.inlineCallbacks and ensureDeferred will now associate a contextvars.Context with the coroutines they run, meaning that ContextVar objects will maintain their value within the same coroutine, …
> Bump minimum version bound on Twisted to 21.2.0.

- changelog.d/18718.misc
- synapse/storage/databases/main/events_worker.py
I noticed this transaction was the top txn by rate on our sliding sync workers,
plus responsible for about 5~10% of database time.
But mostly it'd just makes the database dashboard cleaner not to have this.
<ol>
<li>
Stop querying for background job completeness once they are complete 
</li>
</ol>
> Reduce database usage in Sliding Sync by not querying for background update completion after the update is known to be complete.

- changelog.d/18760.doc.md
- docs/workers.md
Noticed when inspecting https://github.com/element-hq/synapse/pull/18581 that some of the documentation was changed to highlight that there can be multiple workers handling the `receipts` stream & I'm aware of instances running multipe `receipts` workers. Document this on `workers.md` too as this …
> Document that there can be multiple workers handling the receipts stream

- changelog.d/18762.feature
- rust/benches/evaluator.rs
- rust/src/push/base_rules.rs
- rust/src/push/evaluator.rs
- rust/src/push/mod.rs
- synapse/push/bulk_push_rule_evaluator.py
- synapse/storage/databases/main/push_rule.py
- synapse/storage/databases/main/thread_subscriptions.py
- synapse/synapse_rust/push.pyi
- tests/push/test_bulk_push_rule_evaluator.py
- tests/push/test_push_rule_evaluator.py
- tests/storage/test_thread_subscriptions.py
Follows: #18756
Implements: MSC4306
Base: `rei/t2_msc4306_conflict` 
This pull request is commit-by-commit review friendly. 
<ol>
<li>
Add MSC4306's default push rules 
</li>
<li>
Add batch `get_subscribers_to_thread` 
</li>
<li>
Optimise push rule evaluation by getting subscribers in batch 
</li>
</ol>
> Implement the push rules for experimental MSC4306: Thread Subscriptions.

- changelog.d/18751.misc
- synapse/federation/send_queue.py
- synapse/federation/sender/__init__.py
- synapse/handlers/presence.py
- synapse/http/request_metrics.py
- synapse/metrics/__init__.py
- synapse/notifier.py
- synapse/replication/tcp/handler.py
- synapse/replication/tcp/protocol.py
- synapse/storage/database.py
- synapse/storage/databases/main/roommember.py
- synapse/util/ratelimitutils.py
- synapse/util/task_scheduler.py
- tests/metrics/test_metrics.py
This PR reverts https://github.com/element-hq/synapse/pull/18751
@reivilibre [found](https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$u9OEmMxaFYUzWHhCk1A_r50Y0aGrtKEhepF7WxWJkUA?via=matrix.org&via=node.marinchik.ink&via=element.io) that our CI was failing in bizarre ways (thanks for stepping up to dive into this :bow:). Examples:
- `twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 9.`
- `twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended by signal 15.`
<details>
<summary>More detailed part of the log</summary>
https://github.com/element-hq/synapse/actions/runs/16758038107/job/47500520633#step:9:6809
``` …
```
> Revert "Fix `LaterGauge` metrics to collect from all servers (#18751)"

- changelog.d/18780.bugfix
- synapse/_scripts/register_new_matrix_user.py
Fixes the error message in `register_new_matrix_user` for an empty registration shared secret read from file.
| secret     | secret path | file      | result   |
|------------|-------------|-----------|----------|
| empty      | empty       | *         | ✗ NO     |
| empty      | non-empty   | empty     | ✗ EMPTY  |
| empty      | non-empty   | non-empty | ✓        |
| non-empty  | empty       | *         | ✓        |
| non-empty  | non-empty   | *         | ✗ CON    |
- …
> register_new_matrix_user: Fix error message for registration shared secret

- changelog.d/18805.bugfix
- synapse/rest/admin/rooms.py
- tests/rest/admin/test_room.py
> Make the Make Room Admin API choose to puppet the room creator in v12 rooms

- changelog.d/18853.doc.md
- docs/workers.md
Discovered via https://github.com/element-hq/ess-helm/issues/677. Looking at https://github.com/element-hq/synapse/blob/v1.136.0/synapse/rest/admin/__init__.py#L266 only `RoomRestServlet` is generally worker capable. This is just the Room Details API and the v1 Room Delete API and not all the APIs …
> Fix worker documentation around room Admin APIs

- changelog.d/18823.bugfix
- synapse/federation/sender/__init__.py
- synapse/handlers/federation_event.py
We should send events that rescind invites over federation.
Similarly, we should handle receiving such events. Unfortunately, the protocol doesn't make it possible to fully auth such events, and so we can only handle the case where the original inviter rescinded the invite (rather than a room admin).
Complement test: https://github.com/matrix-org/complement/pull/797
> Handle rescinding invites over federation

- changelog.d/18900.misc
- docs/log_contexts.md
- synapse/logging/context.py
- synapse/metrics/background_process_metrics.py
Better explain `LoggingContext` in `run_in_background(...)` and `run_as_background_process(...)`. Also adds a section in the docs explaining the `sentinel` logcontext.
Spawning from https://github.com/element-hq/synapse/pull/18870
1. Run Synapse normally and with `daemonize: true`: `poetry run synapse_homeserver --config-path homeserver.yaml`
1. Execute some requests
1. Shutdown the server
1. Look for any bad log entries in your homeserver logs:
- `Expected logging context sentinel but found main`
- `Expected logging context main was lost`
- `Expected previous context`
- `utime went backwards!`/`stime went backwards!`
- `Called stop on logcontext POST-0 without recording a start rusage`
- `Background process re-entered without a proc`
Twisted trial tests:
1. Run full Twisted trial test …
> Better explain logcontext in `run_in_background(...)` and `run_as_background_process(...)`

- changelog.d/18856.doc
- docs/deprecation_policy.md
Clarify Python dependency constraints
Spawning from https://github.com/element-hq/synapse/pull/18852#issuecomment-3212003675 as I don't actually know the the exact rule of thumb. It's unclear to me what we care about exactly. Our [deprecation policy](https://element-hq.github.io/synapse/latest/deprecation_policy.html) mentions Debian oldstable support at-least for the version of SQLite. But then we only refer to Debian stable for the Twisted dependency:
https://github.com/element-hq/synapse/blob/40edb10a98ae24c637b7a9cf6a3003bf6fa48b5f/pyproject.toml#L179-L186
Arch:
- https://wiki.archlinux.org/title/Python_package_guidelines
- https://wiki.archlinux.org/title/Rust_package_guidelines
Fedora:
- https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/
- Be a short description of your …
> Clarify Python dependency constraints

- changelog.d/18931.doc
- docs/openid.md
This PR addresses https://github.com/element-hq/synapse/issues/17896 by extending the Synapse documentation regarding the necessary `jwt_config` entry in the example on how to connect authentik via OIDC to Synapse.
> OIDC doc: adds missing `jwt_config` values to authentik example

- changelog.d/18933.misc
- synapse/app/admin_cmd.py
- synapse/app/appservice.py
- synapse/app/client_reader.py
- synapse/app/event_creator.py
- synapse/app/federation_reader.py
- synapse/app/federation_sender.py
- synapse/app/frontend_proxy.py
- synapse/app/generic_worker.py
- synapse/app/homeserver.py
- synapse/app/media_repository.py
- synapse/app/pusher.py
- synapse/app/synchrotron.py
- synapse/app/user_dir.py
- synapse/config/_base.py
- tests/app/test_homeserver_start.py
- tests/config/test_registration_config.py
Split loading config vs homeserver `setup`
This allows us to get access to `server_name` so we can use it when creating the `LoggingContext("main")` in the future (pre-requisite for https://github.com/element-hq/synapse/pull/18868).
This also allows us more flexibility to parse config however we want and setup a Synapse homeserver. Like what we do in [Synapse Pro for Small Hosts](https://github.com/element-hq/synapse-small-hosts).
Split out from https://github.com/element-hq/synapse/pull/18868
- End with either a period (.) or an …
> Split loading config vs homeserver `setup`

- changelog.d/18947.misc
- synapse/api/auth/base.py
- synapse/api/errors.py
- tests/api/test_auth.py
> Update MSC4326 error code

- changelog.d/18948.bugfix
- synapse/storage/databases/main/__init__.py
Fixes #18955
The last seen timestamps contained in `/_synapse/admin/v2/users` responses were computed as follows:
```sql
[...]
LEFT JOIN (
SELECT user_id, MAX(last_seen) AS last_seen_ts
FROM user_ips GROUP BY user_id
) ls ON u.name = ls.user_id
[...]
```
https://github.com/element-hq/synapse/blob/4367fb2d078c52959aeca0fe6874539c53e8360d/synapse/storage/databases/main/__init__.py#L302C1-L305C44
This leads to empty timestamps (as in: user was never seen) if users are inactive for longer than [`user_ips_max_age`](https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#user_ips_max_age).
The fix is quite trivial: Use the `devices` table, as this one also contains last seen timestamps but is *not* periodically purged.
We are using this for automatic user …
> fix: Compute user last seen timestamp from last seen devices

- .ci/scripts/triage_labelled_issue.sh
- .github/workflows/triage_labelled.yml
- changelog.d/18913.misc
I got tired of this workflow failing when triaging issues.
The old workflow failed if the item was already on the board. This was partially fixed in https://github.com/element-hq/synapse/pull/18755, which would skip the `actions/add-to-project` step if the issue was already on the board.
However, that meant that the second step now failed, as it now had an empty value for `${{ steps.add_project.outputs.itemId }}`.
---
This PR rips out the `add-to-project` action (which doesn't handle an issue already being on a project) and our old hand-written code and replaces it with new manual code. I tried to look for another action to replace what we had and came across https://github.com/EndBug/project-fields. But that action doesn't support adding the issue to the project.
This new code was mostly …
> Fix `triage_labelled` GHA workflow

- changelog.d/18767.misc
- synapse/res/providers.json
> Updated providers.json to use X instead of Twitter following rebrand and schema change

- changelog.d/18998.doc
- docs/usage/configuration/config_documentation.md
- schema/synapse-config.schema.yaml
*Spawning from a [discussion in `#synapse-dev:matrix.org`](https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$f3ftdeEREjwlH7fdMezFLlcF-Zd5-l6rsR3unPZ6FEY?via=matrix.org&via=node.marinchik.ink&via=element.io),*
https://github.com/element-hq/synapse/commit/8344c944b1f6ee2f398369fcde7e6f643a1ad6e8 introduced the option `rc_room_creation` and the docs are inconsistent, the default is given as:
```yaml
rc_room_creation:
per_user:
per_second: ....
```
while the example shows:
```yaml
rc_room_cration:
per_second: ...
```
Looking at the source code , and the worker example config file, the latter is correct. So simply remove the stray `per_user:` and let's pretend it never existed.
> Fix `rc_room_creation` and `rc_reports` docs - remove `per_user` typo

- changelog.d/19013.misc
- synapse/server.py
Fix bad merge with `start_background_tasks`
This was originally removed in https://github.com/element-hq/synapse/pull/18886 but it looks like it snuck back in https://github.com/element-hq/synapse/pull/18828 during a [bad merge](https://github.com/element-hq/synapse/commit/4cd3d9172ed7b87e509746851a376c861a27820e).
Noticed while looking at Synapse setup and startup (just by happen stance).
I don't think this has adverse effects on Synapse actually working and `start_background_tasks()` can be called multiple times.
As I would like to see the conflicts for each merge.
This works but it's still hard to notice anything is wrong:
```
git log --remerge-diff <commit-sha>
```
> shows the difference from mechanical merge result and the result that is actually recorded in a merge commit
via …
> Fix bad merge with `start_background_tasks`
