element-hq/synapse

changelog.d/16763.doc
docs/usage/configuration/config_documentation.md

* [-] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct

Remove config value from header

---

changelog.d/16769.doc
docs/usage/administration/monitoring/reporting_homeserver_usage_statistics.md

Signed-off-by: Christian Lölkes <christian.loelkes@gmail.com>

Add another custom statistics collection server

---

changelog.d/16780.misc
synapse/handlers/room.py

Fix linting

---

changelog.d/16857.doc
docs/admin_api/rooms.md

fix typo in admin_api/rooms.md

---

changelog.d/16965.doc
docs/upgrade.md

comma splice
"rollback" is a noun

upgrade.md: fix grammatical errors

---

changelog.d/16929.misc
synapse/handlers/sync.py

This is a huge method, which melts my brain.
This is a non-functional change which lays some groundwork for future work in this area.

Split up `SyncHandler.compute_state_delta`

---

changelog.d/16907.misc
synapse/api/constants.py
synapse/handlers/room.py
tests/rest/client/test_rooms.py

Update power level default for public rooms

---

changelog.d/17069.doc
docs/development/contributing_guide.md

Add an OSX prompt to manually configure icu4c.

---

changelog.d/17116.doc
docs/usage/configuration/config_documentation.md

Rephrase enable_notifs configuration

---

changelog.d/17114.doc
docs/admin_api/room_membership.md
docs/message_retention_policies.md
docs/postgres.md
docs/setup/installation.md
docs/usage/administration/admin_api/background_updates.md
docs/usage/administration/admin_faq.md
docs/user_directory.md
docs/workers.md

Fix various typos in docs

---

changelog.d/17082.feature
synapse/rest/client/versions.py

Pretty straightforward. 😄 
Fixes #17021

Declare support for Matrix v1.10.

---

changelog.d/17141.docker
docker/Dockerfile

Correct licensing metadata on the Docker image

---

changelog.d/17148.doc
scripts-dev/lint.sh

Fix lint.sh script

---

changelog.d/17166.misc
synapse/handlers/profile.py
synapse/handlers/sso.py

Linter errors are showing up in #17147 that are unrelated to that PR. The errors do not currently show up on develop.
This PR aims to resolve the linter errors separately from #17147.

Fix undiscovered linter errors

---

changelog.d/17204.doc
docs/openid.md

Signed-off: Xavier Guimard <xguimard@linagora.com / yadd@debian.org>

Update Lemonldap-NG OIDC config

---

changelog.d/17348.doc
docs/usage/configuration/config_documentation.md

Correct error in user_directory docs

---

docs/usage/configuration/config_documentation.md

Fix refreshable_access_token_lifetime typo

---

README.rst
changelog.d/17379.doc

I don't think this warrants a changelog?

Fix links in README

---

CHANGES.md
changelog.d/17365.feature

Fix links to MSC3916

---

changelog.d/17403.feature
synapse/rest/client/versions.py

Previous: https://github.com/element-hq/synapse/pull/17082
Fixes https://github.com/element-hq/synapse/issues/17402
See https://github.com/element-hq/synapse/issues/17402 for context
**Blocked on https://github.com/element-hq/synapse/pull/17388** (required for spec compliance)

Declare support for Matrix 1.11

---

debian/templates

Update debian template - new link to the delegation docs

Update debian template - new link to the delegation docs

---

changelog.d/17569.misc
synapse/media/_base.py

Fix 'Producer was not unregistered' error

---

changelog.d/17594.doc
docs/usage/configuration/config_documentation.md

docs: fix typo in saml2_config example

---

changelog.d/17672.misc
synapse/handlers/sliding_sync/room_lists.py
synapse/types/handlers/sliding_sync.py
tests/rest/client/sliding_sync/test_rooms_meta.py

A couple of small performance improvements for sliding sync.

Small performance improvements for sliding sync

---

README.rst

Fix minor misspelling in README.rst.

---

changelog.d/17802.doc
docs/workers.md

Fix incorrectly documented config path argument

---

.github/workflows/release-artifacts.yml
changelog.d/17905.misc

Use unique name for each os.arch variant when uploading Wheels

---

changelog.d/17907.bugfix
synapse/logging/_remote.py
tests/server.py

There's also https://github.com/element-hq/synapse/pull/17906

Fix other unit tests with latest twisted

---

changelog.d/17931.doc
docs/SUMMARY.md
docs/postgres.md
docs/setup/installation.md
docs/usage/administration/backups.md
docs/usage/configuration/config_documentation.md

Fixes: https://github.com/element-hq/element-meta/issues/2155
Fixes: https://github.com/element-hq/synapse/issues/2046

Add some documentation about backing up Synapse

---

changelog.d/17953.doc
contrib/docker/README.md
contrib/docker_compose_workers/README.md

breadcrumb trail to element-docker-demo from contrib/docker*

link to element-docker-demo from contrib/docker*

---

changelog.d/17846.misc
docs/setup/installation.md

Update Alpine Linux Synapse Package Maintainer within installation.md as it is outdated.
* [N/A] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
(run the …

Update Alpine Linux Synapse Package Maintainer within installation.md

---

changelog.d/17992.doc
synapse/util/task_scheduler.py

As I found the current docstrings a bit unclear while trying to wrap my head around this class.

Wording improvements for the `TaskScheduler`

---

changelog.d/18089.bugfix
contrib/docker/docker-compose.yml

Closes https://github.com/element-hq/synapse/issues/18088.

Contrib: Docker: updates PostgreSQL version in `docker-compose.yml`

---

changelog.d/18165.bugfix
synapse/storage/databases/state/store.py
tests/storage/test_purge.py

Cleanup deleted state group references

---

.ci/before_build_wheel.sh
.github/workflows/release-artifacts.yml
Cargo.lock
changelog.d/18213.misc
rust/Cargo.toml

Actually fix CI build wheels.

---

changelog.d/18224.doc
docs/workers.md

Closes: https://github.com/element-hq/synapse/issues/17926

Fix: corrected routing path for workers doc

---

changelog.d/18276.doc
docs/sso_mapping_providers.md

Correct typo "SAML" -> SSO in mapping providers docs

---

changelog.d/18272.docker
docker/Dockerfile-workers
docker/complement/Dockerfile

Docker: Use an ARG for debian version more often

---

changelog.d/18273.docker
docker/complement/conf/start_for_complement.sh

Pass args to start_for_complement.sh

---

changelog.d/18337.misc
synapse/handlers/device.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/registration.py

We call these two functions for every authed request when using delegated auth.

Add caches to new hot path functions

---

changelog.d/18369.misc
synapse/api/ratelimiting.py
synapse/rest/client/sync.py
tests/api/test_ratelimiting.py

Slight performance increase when using the ratelimiter

---

README.rst
changelog.d/18218.doc

Readme tweaks

---

changelog.d/18380.misc
synapse/notifier.py

Context: https://github.com/element-hq/synapse/issues/17791#issuecomment-2845458960

remove room without listeners from Notifier.room_to_user_streams

---

changelog.d/18445.doc
docs/postgres.md

Added Postgres major version upgrade to include e2e_one_time_keys_json truncate info.

Add advice for upgrading between major postgres versions to documentation

---

changelog.d/18516.doc
docs/SUMMARY.md

The docs were created in:
- #18214
It will have been an oversight that the docs were not added to the `SUMMARY.md` (TOC). 

docs: render missing docs for scheduled tasks admin api

---

.github/workflows/schema.yaml
changelog.d/18551.misc

... and release branches, so that we catch any problems that slip trough PR review.

Always run schema workflow on develop

---

changelog.d/18625.misc
synapse/storage/controllers/purge_events.py

So we can see what we're deleting.

Log the room ID we're purging state for

---

synapse/api/auth/msc3861_delegated.py

Update msc3861_delegated.py spelling correction

---

changelog.d/18729.misc
synapse/__init__.py
synapse/handlers/send_email.py

Follows: #18727 
<ol>
<li>
Remove obsolete Twisted version checks 
</li>
</ol>

Remove some obsolete Twisted version checks.

---

docs/structured_logging.md

fix(docs): Update structured_logging.md for file handler config
